### ISSUE TITLE
Support workspaceSymbol

### ISSUE THREAD

**Issue by matklad** [ul/kak-lsp#104]
Hi!

As a heavy IDE user, I find "workspaceSymbol" the most important command IDE has to offer!

It would be cool if kak-lsp supported it :)

**Comment by ul** [comment]
I've added `lsp-workspace-symbol` command which takes query as the only parameter. Then it opens result as a separate buffer. Rendering buffer is implemented as `lsp-show-workspace-symbol` which you can override to, for example, pass matches to fuzzy finder instead. `lsp-show-workspace-symbol` takes two parameters, first one is project root and second is a list of matches in `*grep*`-buffer-like format (passed as a single string).

**Comment by matklad** [comment]
Verified that it works!

One thing here is that fuzzy matching is already built into workspace/symbols request. So ideally, the user-visible UI should be an input-field for a query plus a listing of the results, such that results are automatically updated when the input field changes, and "update" is basically a fresh `$workspace/symbols` request to the language server.

So, internally having an `lsp-worksapce-symbol` command with one argument which returns a list of strings is right, but the ideal user-visible API probably should not expose that directly, instead wrapping it into some kind of incremental search UI.

**Comment by ul** [comment]
Yes, it's a good idea, I just didn't realize that it's possible to do with Kakoune builtin functionality. Now I think that [prompt](https://github.com/mawww/kakoune/blob/master/doc/pages/commands.asciidoc#helpers) with `-on-change` callback is enough to implement it.

**Comment by ul** [comment]
As uncovered it's non-trivial to use `-on-change` with arbitrary commands, but I think I got decent solution. I added `lsp-workspace-symbol-incr` command which does incremental search using `prompt` for query input.

Feel free to re-open this issue or create a new one if you think command's UX should be improved or you hit any bugs.
