### ISSUE TITLE
lsp user mode

### ISSUE THREAD

**Issue by ul** [ul/kak-lsp#105]
There is undocumented lsp user mode since last release https://github.com/ul/kak-lsp/blob/a8e7830629108aef42ccaa61bf4d651ae7e54220/rc/lsp.kak#L475

I'd like to ask feedback on those keybinding before I put them into README because I don't want to change them much after that, only extend.

How sensible do they look for you, taking in account that more commands corresponding to LSP requests will be added in feature, so should we reserve any of the letters for more important stuff?

**Comment by vbauerster** [comment]
`lsp-highlight-references` is missing, suggest add it as well, for example:
```
map global lsp <&> ': lsp-highlight-references<ret>' -docstring 'lsp-highlight-references'
```
