### ISSUE TITLE
language_features::formatting::editor_formatting generates invalid Kakoune script on empty text edit

### ISSUE THREAD

**Issue by dgrisham** [ul/kak-lsp#121]
The latest update to `lsp-formatting-sync` in [this commit](https://github.com/ul/kak-lsp/commit/81f7641d28c3681396ceeeaf0cf644a9232baceb) seems to have introduced a bug for me. Whenever I run the command (via hook or otherwise), I get this error:

```
error running hook BufWritePre(/home/grish/test.py)/lsp: 1:1: 'lsp-formatting-sync' 3:25: 'eval' 1:1: 'eval' 1:1: 'select' wrong argument count
```

**Comment by ul** [comment]
Works flawlessly on my side. Would you mind posting kak-lsp log?

Just to double-check, versions which I use:

```
06:06 ~/t/test_py ❯ kak -version
Kakoune v2018.09.04-147-gda13b5f8
06:07 ~/t/test_py ❯ kak-lsp --version
kak-lsp 5.8.2
```

**Comment by dgrisham** [comment]
Ah, I narrowed it down to a more specific case -- it seems to happen only when the buffer isn't altered by `lsp-formatting-sync`. It seems to work otherwise.

Here's the version info in case that's still helpful:

```
$ kak -version
Kakoune v2018.09.04-171-g365407c3
$ kak-lsp --version
kak-lsp 5.8.2
```

**Comment by ul** [comment]
Thanks for investigating! Then it must be a long-standing problem of `lsp-formatting` as well which just doesn't handle well empty text edit and is not related to the latest update.

**Comment by dgrisham** [comment]
Interesting, is that error somehow suppressed by the regular `lsp-formatting` command? Because I don't get the error when I run that one. Also, let me know if you still want the log output.

**Comment by ul** [comment]
I was able to reproduce it with the regular `lsp-formatting`, not sure why is it suppressed on your side.

**Comment by ul** [comment]
Yes, log could be helpful to investigate that difference in behaviour of commands.

**Comment by dgrisham** [comment]
Figured it out, I see the error in both the status bar and the debug buffer when I run `lsp-formatting-sync` but only in the debug buffer for `lsp-formatting`.
