### ISSUE TITLE
extra bullet point for new line

### ISSUE THREAD

**Issue by Delapouite** [ul/kak-lsp#124]
Hi.

I'm using ksk-lsp with https://github.com/theia-ide/typescript-language-server. I haven't checked how this server formats its responses yet but here's how the info looks:

![image](https://user-images.githubusercontent.com/39315/47870226-54962c80-de09-11e8-85e7-17fd60a59d81.png)

![image](https://user-images.githubusercontent.com/39315/47870233-5b24a400-de09-11e8-96c3-14382358b576.png)

There's often an extra bullet in front of blank lines (indicated by the green arrow on the screenshots).
The bullets were introduced in https://github.com/ul/kak-lsp/issues/66 . There seems to be something strange with the handling of newlines somehow.

**Comment by ul** [comment]
Prima facie it looks like a bug in typescript-language-server, as I get the following response from it:
```json
{
  "jsonrpc": "2.0",
  "id": 1,
  "result": {
    "contents": [
      {
        "language": "typescript",
        "value": "(property) require: any"
      },
      "" <-- Note this empty string
    ],
    "range": {
      "start": {
        "line": 0,
        "character": 13
      },
      "end": {
        "line": 0,
        "character": 20
      }
    }
  }
}
```

OTOH, I think kak-lsp should filter out empty strings anyway.

**Comment by ul** [comment]
Binaries with workaround will be available soon at https://github.com/ul/kak-lsp/releases/tag/v5.9.1, but I also suggest to post an issue for typescript-language-server.
