### ISSUE TITLE
Allow user-provided InitializeParams

### ISSUE THREAD

**Issue by topisani** [ul/kak-lsp#126]
Could be either in the kakoune config or per language server in kak-lsp. Optimally maybe both.

Example of why we would want this: https://github.com/eclipse/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line

**Comment by ul** [comment]
Implementing #159 as having an option on Kakoune side which contains all running language servers will allow knowing when to bundle InitializeParams with the request.

**Comment by ul** [comment]
Or, even better, kak-lsp could ask Kakoune for InitializeParams before sending initialize request. The benefit of it that it will set the precedent of communication in that direction which could be useful in other cases as well.

**Comment by ul** [comment]
Just realized that per language server it's already supported in kak-lsp.toml as "initialization_options" field. What left is to allow override from Kakoune option to make it suitable for per-project use.

**Comment by ul** [comment]
It's even documented in the readme. Sorry that I totally forgot about it and didn't check properly (and for the train of comments.)
