### ISSUE TITLE
Language detection based on kakoune filetype option

### ISSUE THREAD

**Issue by JJK96** [ul/kak-lsp#134]
At the moment both kakoune and kak-lsp detect the filetype of a file. 

I think it would be better (if it is possible) to let kakoune define which language a given file is in based on the filetype option.

**Comment by ul** [comment]
Yes, it's totally possible. We can introduce an extra field in request `[meta]` section. I just thought that it's redundant information as it can be inferred from `buffile`.

**Comment by JJK96** [comment]
In most cases we can indeed infer it from the buffer file, however some languages use the same extension. 
In short, extension to filetype is not a one-to-one map.

**Comment by JJK96** [comment]
Nice implementation, I have been testing and I ran into 2 (semi) problems.

1. for different filetypes that use the same server (c,cpp), the entry should be duplicated for these filesystems, maybe there should be a way to match them with an or statement. 
2. The extensions field in the toml file is still required.

**Comment by ul** [comment]
Good catch! I think problem could be solved by replacing `extensions` with `filetypes` and making entry key arbitrary again.

**Comment by ul** [comment]
Now it seems to work, but just realized that it's a breaking change (in case someone uses custom config). I should pack few more before release then =)
