### ISSUE TITLE
lsp-rename-prompt should default to the current name

### ISSUE THREAD

**Issue by Screwtapello** [ul/kak-lsp#137]
Steps to reproduce:

 1. In a file with a supported language server, select a name
 2. `:lsp-rename-prompt`

Expected result:

  - A "New name" prompt with the current name filled in, so it can be edited

Actual result:

  - A "New name" prompt with no initial value, so to make a minor change I have to copy/paste the name from the buffer into the prompt.

**Comment by ul** [comment]
Yes, that's sound reasonable. I was unsure if including `lsp-rename-prompt` is too much as users could roll it or any variation of it on top of `lsp-rename` easily. But it's already there, let's improve it.
