### ISSUE TITLE
Upgrade crossbeam_channel

### ISSUE THREAD

**Issue by ul** [ul/kak-lsp#144]
This library provides the main communication utility of kak-lsp, it would be nice to keep it up-to-date. But because of API change upgrade task requires extra attention.

**Comment by matklad** [comment]
Re select, I am not sure, but looks like the Select s truck is the way to go

**Comment by matklad** [comment]
Btw, you might be interested in this (recently extracted) file: https://github.com/rust-analyzer/rust-analyzer/blob/f3ea21ac16481de1197c9daadee3be96546974b5/crates/thread_worker/src/lib.rs

It deals with spawning and managing a worker thread which processes events in a loop. There are a number of subtitles there:

* a thread is better be joined in the end, so this is checked
* to avoid deadlocks, the buffer size has to be unlimited on at least one side
* after stopping the worker, you might still have some pending responses from the worker.

Note that this still uses old crossbeam though.

**Comment by ul** [comment]
Thank you, I think I should adopt this structured approach.
