### ISSUE TITLE
Jump to reference

### ISSUE THREAD

**Issue by JJK96** [ul/kak-lsp#151]
the `lsp-references` command creates a buffer with references in the format: `path_to_file:line:column`. 
I have created a small function to jump to the indicated location of such a reference. 

I am not sure if this is worth including in kak-lsp, but if you want I can create a PR.

```
define-command open-location %{
    execute-keys xs^.*?(:\d+){1,2}<ret>
    evaluate-commands %sh{
        echo "edit $kak_selection" | sed -e "s/:/ /g"
    }
}
```

**Comment by ul** [comment]
kak-lsp implicitly depends on https://github.com/mawww/kakoune/blob/master/rc/core/grep.kak for jumps (filetype of `*references*` buffer is `grep`), but it might worth adding this command straight into `lsp.kak` for those who don't use `grep.kak`.

**Comment by JJK96** [comment]
Ah there is a `grep-jump` command, I couldn't find it.
I would say, make the optional dependency on grep.kak explicit and let users handle it.
