### ISSUE TITLE
How to turn on semantic highlighting for cquery?

### ISSUE THREAD

**Issue by ebetica** [ul/kak-lsp#152]
I saw that it was added in  #14, and i can see cquery_semhl in the list of highlighters, but I do not see nice semantic highlighting in my terminal. How can I enable it?

**Comment by ul** [comment]
Do other cquery-specific features work?

I think it worth checking `*debug*` buffer for errors and also to run kak-lsp in verbose mode and log its output (see Troubleshooting section in README for details) and checking if `$cquery/publishSemanticHighlighting` notification from cquery is delivered, has proper content and is properly processed. If you will post the log, I'll help you to diagnose it.

**Comment by ebetica** [comment]
cquery works like a charm, thanks for all your hard work on this. I'm able to see the real types of variables, jump to definition, and get autocompletion results.

I checked both things, and the only thing I found of note are:

*debug*:
```
error running command 'eval -client  'lsp-show-error ''Language server is not initialized, parking request'''': 1:1: 'eval' wrong argument count 
```

example of a completion request log: https://gist.github.com/ebetica/12126879a1b5b6204982a7b041b5ad94

I did not find publishSemanticHighlighting anywhere from the debug log unfortunately.

**Comment by ul** [comment]
It might be something with cquery configuration. Would you mind trying VS Code with the cquery extension on your project? If semantic highlighting works in VS Code, we can investigate the difference between it and kak-lsp case. If it doesn't work, I'd advice looking for help from the cquery community.

**Comment by andreyorst** [comment]
I can confirm that there's no semantic highlighting with cquery

**Comment by ul** [comment]
Is anyone keen to provide an example project with a proper cquery configuration which I can test against?

**Comment by ebetica** [comment]
I tried to reproduce this on the cquery project in vscode, but I can't seem to get that working either... It's very easy to set up:

```
# compile / install cquery
git clone https://github.com/cquery-project/cquery
cd cquery
git submodule update --init
mkdir build && cd build
cmake .. -DCMAKE_INSTALL_PREFIX=$YOUR_INSTALL_PREFIX_HERE -DCMAKE_EXPORT_COMPILE_COMMANDS=YES -DCMAKE_BUILD_TYPE=Release
cmake --build .
cmake --build . --target install

ln -s build/compile_commands.json
```

Then, I get code autocompletions, include the class name, etc, but no semantic highlighting.

**Comment by andreyorst** [comment]
I've had semantic highlighting on my projects in emacs with lsp-mode and emacs-cquery package.

**Comment by ul** [comment]
Apparently, semantic highlighting needs to be explicitly enabled via params. I pushed an update for default `kak-lsp.toml` to include it.

Note that you still need to define faces to see actual colours. Names of faces are defined here https://github.com/ul/kak-lsp/blob/b2960b090449d9696713341bd0b4d0a2ccaffd03/src/language_features/cquery.rs#L123

PR with some reasonable default values for faces (probably by defining them in terms of built-in/common Kakoune faces) is more than welcome!

**Comment by andreyorst** [comment]
> PR with some reasonable default values for faces (probably by defining them in terms of built-in/common Kakoune faces) is more than welcome!

Does this need to be inside `kak-lsp`? Maybe other servers are defining their own faces, and this should be split to separate plugin that will add those for desired server? Like it is done in Emacs -- they have lsp-mode packagre which is a client for LSP and emacs-cquery package that works with lsp-mode defining cquery specific things

**Comment by ul** [comment]
Yes, that would work too. I don't have a strong opinion here.

**Comment by andreyorst** [comment]
Is there any other cquery related stuff that can be put to such supplement plugin?

**Comment by ul** [comment]
At the moment the only cquery-specific stuff we have is processing `$cquery/publishSemanticHighlighting` notification. To move it to the separate plugin will require to add the notion of plugins to kak-lsp itself because it's not only Kakoune script code, but also Rust code involved in such processing.
