### ISSUE TITLE
Error right after startup

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#155]
After creating template project with  cargo and opening `main.rs` I'm getting this error.

```
error running command 'eval -client  'lsp-show-error ''Language server is not initialized, parking request'''': 1:1: 'eval' wrong argument count
```

Seems like that kak-lsp tries to enable `lsp-diagnostic-lines` but there's no server running yet

**Comment by ul** [comment]
Let me know if I fixed a different problem =)

**Comment by andreyorst** [comment]
The issue still persists:
```
*** This is the debug buffer, where debug info will be written ***
Dependency unmet: gocode, please install it to use go-tools
Dependency unmet: goimports, please install it to use go-tools
Dependency unmet: gogetdoc, please install it to use go-tools
Dependency unmet: jq, please install it to use go-tools
Config-change detected:
Config-change detected: rust.clippy_preference="on"
error running command 'eval -client  'lsp-show-error ''Language server is not initialized, parking request'''': 1:1: 'eval' wrong argument count
```

**Comment by andreyorst** [comment]
I don't mind the actual error with uninitalized server though, just bothered by kakoune not executing an `evaluate-command` properly

**Comment by ul** [comment]
I think this is related to https://github.com/mawww/kakoune/issues/1872 as `lsp-did-open` is usually executed either on `BufCreate` (when using `lsp-enable`) or on `WinSetOption` (typical use of `lsp-enable-window`).

As the current solution, I'm going to remove `lsp-did-open` call from both commands. `textDocument/didOpen` request is anyway injected by kak-lsp server when it routes any other request and `textDocument/didOpen` was not sent yet.

**Comment by ul** [comment]
Ah, we still need to send `lsp-did-change-config` in those hooks, which would lead to the same problem. Okay, then I'm going ignore empty client when sending the response. As far as I can see it should be harmless.
