### ISSUE TITLE
LSP does not work for newly created (not saved) files

### ISSUE THREAD

**Issue by ikalnytskyi** [ul/kak-lsp#156]
Hey @ul,

Thanks for the plugin, it works really great. I found annoying bug, here's some details:

**Repro steps**:

* Create but not save a file using `kak` with enabled `kak-lsp`. Example: `kak foo.py`.
* Type `imp` and wait for completion.

**Expected behaviour**:

* A list of completion items from the language server.

**Actual behaviour**:

* An error is shown instead of completions.

---

I tracked down the problem to  `text_document_did_open` function. The problem is that kak-lsp program tries to read a file from filesystem in order to send its content to a language server, however, new (not saved) files cannot be found yet.

https://github.com/ul/kak-lsp/blob/e0bb7c16bcfaa05fefa166c52052ffb88d0e9080/src/text_sync.rs#L10-L32

I think `lsp.kak` should send a buffer's content to `kak-lsp` for `lsp-did-open` even the same way it sends the content for `lsp-did-change` event. Alternatively, we can send an empty "text" if file not found in `text_document_did_open` and trigger `lsp-did-change` right after `lsp-did-open` in `lsp.kak`.

**Comment by ul** [comment]
Hey, thanks for reporting! Yes, I agree, it worth changing `lsp-did-open` behaviour to align with `lsp-did-change` one.
