### ISSUE TITLE
`lsp-formatting-sync` hangs when language server is not running

### ISSUE THREAD

**Issue by lePerdu** [ul/kak-lsp#158]
If `lsp-formatting-sync` is run on a buffer for which there is no language server, the command blocks indefinitely.

Related: #119

kak version: Kakoune v2019.01.20
kak-lsp version: current git (e504ec90)

**Comment by ul** [comment]
Thank you for reporting! I think this is better to be solved by proper handling on kak-lsp server side (similar to how #119 was fixed), rather than Kakoune side. In general, it's not trivial to maintain up-to-date information about LSP server status on Kakoune side.
