### ISSUE TITLE
textDocument/documentSymbol DocumentSymbol[] response not handled

### ISSUE THREAD

**Issue by daboross** [ul/kak-lsp#163]
Hi,

Ran into this trying to use `kak-lsp` with [`rust-analyzer`]. `kak-lsp` sends a request for `textDocument/documentSymbol`, and I get the following in the log:

```
Feb 10 00:16:18.549 DEBG From editor: 
session  = "2214"
client   = "client0"
buffile  = "/home/daboross/lsp-test/src/main.rs"
filetype = "rust"
version  = 26
method   = "textDocument/documentSymbol"
[params]
, module: kak_lsp::editor_transport:151
Feb 10 00:16:18.549 DEBG Routing editor request to Route { session: "2214", language: "rust", root: "/home/daboross/lsp-test" }, module:
 kak_lsp::session:117
Feb 10 00:16:18.549 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///hom
e/daboross/lsp-test/src/main.rs"}},"id":26}, module: kak_lsp::language_server_transport:149
Feb 10 00:16:18.549 DEBG From server: {"jsonrpc":"2.0","id":26,"result":[{"deprecated":false,"detail":"fn()","kind":12,"name":"main","ra
nge":{"end":{"character":1,"line":9},"start":{"character":0,"line":5}},"selectionRange":{"end":{"character":7,"line":5},"start":{"charac
ter":3,"line":5}}},{"children":[{"deprecated":false,"detail":"u32","kind":13,"name":"field","range":{"end":{"character":14,"line":2},"st
art":{"character":4,"line":2}},"selectionRange":{"end":{"character":9,"line":2},"start":{"character":4,"line":2}}}],"deprecated":false,"
kind":23,"name":"X","range":{"end":{"character":1,"line":3},"start":{"character":0,"line":0}},"selectionRange":{"end":{"character":8,"li
ne":1},"start":{"character":7,"line":1}}}]}thread ', <unnamed>module' panicked at ':Failed to parse document symbol response: Error("mis
sing field `location`", line: 0, column: 0) ', kak_lsp::language_server_transport:129src/libcore/result.rs
:997:5
Feb 10 00:16:18.550 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:160
Feb 10 00:16:18.550 ERRO Failed to join controller thread, module: kak_lsp::session:75
Feb 10 00:16:18.740 ERRO Language server error: Error: ErrorMessage { msg: "client exited without shutdown" }
... continued error message from rust-analysis failing
```

I don't know the lsp spec well, but from what I can find, the problem is that rust-analyzer is returning a `DocumentSymbol[]`, while kak-lsp expects it to be a `SymbolInformation[]`.

[The spec for `textDocument/documentSymbol`](https://microsoft.github.io/language-server-protocol/specification#textDocument_documentSymbol) states that the language server can return either `SymbolInformation[]` or `DocumentSymbol[]`. 

`rust-analyzer` returns `DocumentSymbol[]`:

```json
{"jsonrpc":"2.0","id":26,"result":[{"deprecated":false,"detail":"fn()","kind":12,"name":"main","range":{"end":{"character":1,"line":9},"start":{"character":0,"line":5}},"selectionRange":{"end":{"character":7,"line":5},"start":{"character":3,"line":5}}},{"children":[{"deprecated":false,"detail":"u32","kind":13,"name":"field","range":{"end":{"character":14,"line":2},"start":{"character":4,"line":2}},"selectionRange":{"end":{"character":9,"line":2},"start":{"character":4,"line":2}}}],"deprecated":false,"kind":23,"name":"X","range":{"end":{"character":1,"line":3},"start":{"character":0,"line":0}},"selectionRange":{"end":{"character":8,"line":1},"start":{"character":7,"line":1}}}]}
```

But kak-lsp only parses it as `SymbolInformation[]`:

https://github.com/ul/kak-lsp/blob/202dc640d600339bd6c03f72e06ff8efc7c33ab3/src/language_features/document_symbol.rs#L32-L33

Right now I'm not seriously using `kak-lsp` with `rust-analyzer`, but I'd like to, so I'm going to try to report all the errors I find when using them together. I _think_ this particular error is on kak-lsp's side of things, but if it isn't then I can definitely make an error report in `rust-analyzer` as well. [`rust-analyzer` doesn't support client capabiiities](https://github.com/rust-analyzer/rust-analyzer/issues/144) so that might be a problem? I don't think it is the case for this, though.

If there's anything I've misunderstood, please let me know! Or if there's more information I can provide.

[`rust-analyzer`]: https://github.com/rust-analyzer/rust-analyzer

**Comment by ul** [comment]
Hey, thanks for the detailed report! (And prompt PR ;-) )

Yes, I definitely interested in supporting rust-analyzer, though this case boils down to properly supporting spec =)

**Comment by ul** [comment]
I added basic handling for DocumentSymbol in response. Please let me know if you encounter any problems with it.
