### ISSUE TITLE
textDocument/definition response LocationLink[] not handled

### ISSUE THREAD

**Issue by daboross** [ul/kak-lsp#164]
As with #163, this is something I found experimenting with [`rust-analyzer`].

Per the [Goto Definition spec](https://microsoft.github.io/language-server-protocol/specification#textDocument_definition), the language server is allowed to return `Location`, `Location[]`, or `LocationLink[]`.

lsp-types's `GotoDefinitionResponse` handles the `LocationLink[]` case:

https://github.com/gluon-lang/lsp-types/blob/619efd0cc07fbb9d0931026fe2fdf7724ece4039/src/request.rs#L267-L271

But, the type `GotoDefinitionResponse` defined in `src/types.rs` doesn't, as far as I can tell:

https://github.com/ul/kak-lsp/blob/4ac1e89aa99f8abab60b6509f03abb123ad0c0bb/src/types.rs#L170-L174

`rust-analyzer` returns `LocationLink[]`, though. So when I try to run `lsp-definition` with `rust-analyzer`, then, I get the following error:

```
Feb 10 02:21:08.272 DEBG From editor: 
session   = "3800"
client    = "client0"
buffile   = "/home/daboross/lsp-test/src/main.rs"
filetype  = "rust"
version   = 1
method    = "textDocument/definition"
[params.position]
line      = 7
character = 15
, module: kak_lsp::editor_transport:151
Feb 10 02:21:08.272 DEBG Routing editor request to Route { session: "3800", language: "rust", root: "/home/daboross/lsp-test" }, module: kak_lsp::session:117
Feb 10 02:21:08.272 DEBG To server: {"jsonrpc":"2.0","method":"textDocument/definition","params":{"position":{"character":15,"line":7},"textDocument":{"uri":"file:///home/daboross/lsp-test/src/main.rs"}},"id":1}, module: kak_lsp::language_server_transport:149
Feb 10 thread '0<unnamed>2' panicked at ':Failed to parse definition response: Error("data did not match any variant of untagged enum GotoDefinitionResponse", line: 0, column: 0)21', :src/libcore/result.rs0:9997.:3925 
DEBGnote: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
 From server: {"jsonrpc":"2.0","id":1,"result":[{"originSelectionRange":{"end":{"character":19,"line":7},"start":{"character":14,"line":7}},"targetRange":{"end":{"character":14,"line":2},"start":{"character":4,"line":2}},"targetSelectionRange":{"end":{"character":9,"line":2
},"start":{"character":4,"line":2}},"targetUri":"file:///home/daboross/lsp-test/src/main.rs"}]}, module: kak_lsp::language_server_transport:129
Feb 10 02:21:09.393 DEBG Received signal to stop language server, closing pipe, module: kak_lsp::language_server_transport:160
Feb 10 02:21:09.393 ERRO Failed to join controller thread, module: kak_lsp::session:75
Feb 10 02:21:09.757 DEBG Language server closed pipe, stopping reading, module: kak_lsp::language_server_transport:107
Feb 10 02:21:09.757 ERRO Language server error: ERROR [ra_lsp_server::main_loop] unhandled notification: RawNotification { method: "workspace/didChangeConfiguration", params: Object({"settings": Object({})}) }
ERROR [ra_lsp_server::main_loop] unhandled notification: RawNotification { method: "workspace/didChangeConfiguration", params: Object({"settings": Object({})}) }
Error: ErrorMessage { msg: "client exited without shutdown" }

stack backtrace:
... error from rust-analyzer
```

It's a bit garbled, but shows that ra_lsp_server (rust-analyzer) returns a json that looks like a `LocationLink[]`, and kak-lsp fails to parse it.

I _think_ the solution here is to remove `types::GotoDefintiionResponse` in favor of `Option<languageserver_types::request::GotoDefinitionResponse>` then just grab the location information out of `LocationLink` and map it to `Location`, but that might be naive of me? If that sounds like a good solution, I'd be happy to contribute a pull request.

[`rust-analyzer`]: https://github.com/rust-analyzer/rust-analyzer

**Comment by ul** [comment]
Thanks for the report and prompt PR! Yes, I created own `GotoDefintionResponse` when it was not available in languageserver_types and I think that spec didn't include LocationLink at that point (I might be wrong). And then I just forgot to change it, there is no specific reason to keep own definition anymore. So, you analysis is totally correct.

**Comment by daboross** [comment]
Thanks!
