### ISSUE TITLE
Update crate lsp-types to 0.56.0 to pick up fix to panic

### ISSUE THREAD

**Issue by vnagarnaik** [ul/kak-lsp#167]
A recent PR gluon-lang/lsp-types#100 fixes a panic in kak-lsp when a language server sends `activeSignature:-1` to indicate an invalid/ignored value. Update to version 0.56.0 to fix the panic. Also need to validate `(activeSignature >= 0 && activeSignature < signatures.size())` when parsing SignatureHelp message.

**Comment by vnagarnaik** [comment]
Thanks for quickfix.

**Comment by ul** [comment]
No worries, please let me know if you'll encounter any problems with it.
