### ISSUE TITLE
Use underscore to show warnings and errors instead of coloring text

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#170]
Can this be done?

**Comment by ul** [comment]
Something like
```
set-face global DiagnosticError default+u
set-face global DiagnosticWarning default+u
```
should do the job.

**Comment by andreyorst** [comment]
Ah, I've thought that LSP defines it's own highlighter for that.

**Comment by andreyorst** [comment]
![image](https://user-images.githubusercontent.com/19470159/53227613-c41d7980-368f-11e9-8d31-0f23addcaedb.png)

I wonder why whitespace is highlighted?

**Comment by ul** [comment]
Either language server reported such range or kak-lsp translated it improperly. Looking into the debug log and comparing positions might help to figure out what happened.

**Comment by ul** [comment]
I'm curious if you were able to figure at which point highlight range get screwed.

**Comment by andreyorst** [comment]
I suppose the highlighting itself works fine, and the problem (if it is a problem) is in calculation of all positions, because in this example the warning box also will be shown when the cursor is placed on the whitespace.

**Comment by ul** [comment]
Yes, but I wonder at which stage you get the wrong position: is it language server or kak-lsp itself, as I don't get problems you described with RLS, for example.

**Comment by andreyorst** [comment]
Seems so. Maybe cquery providing wrong coordinates, or they are being parsed wrongly. Maybe compare what cquery and rls are providing?

**Comment by ul** [comment]
Partially it was a problem with kak-lsp — it didn't convert zero-length ranges properly. I just fixed it. But there is another problem with cquery — it shouldn't return zero-length range in such case, but rather range covering the entire identifier.

**Comment by andreyorst** [comment]
perhaps this should be reported to cquery. I wonder how ccls server behaves
