### ISSUE TITLE
python-language-server prints placeholders

### ISSUE THREAD

**Issue by maximbaz** [ul/kak-lsp#171]
```
$ kak -n /tmp/test.py

:set buffer filetype python
source /usr/share/kak-lsp/rc/lsp.kak
lsp-enable
```

Now type `print` and press `C-n` to select the first (and only) entry in the autocomplete. 

Here's what will appear in the buffer:

```
print(${1:value}, ${2:...}, ${3:sep}, ${4:end}, ${5:file}, ${6:flush})$0
```

Reproduced on Arch Linux with `kak-lsp 6.0.1` and `python-language-server 0.24.0`

![peek 2019-02-21 23-45](https://user-images.githubusercontent.com/1177900/53207003-d1f0e180-3632-11e9-9161-13747488f93e.gif)

**Comment by ul** [comment]
kak-lsp doesn't set snippetSupport flag explicitly. It looks like python-language-server either treat it as true by default or ignores it completely (the latter is the most likely from the quick glance at the code).

Chances are that some other language servers do the same and some kak-lsp users depend on this behaviour and use snippets.

So it might worth introducing an option in kak-lsp and both sending explicit snippetSuport based on it and filtering out snippets by insertTextFormat (if it is set properly by language server) when the option is false.

**Comment by maximbaz** [comment]
Upstream bug: https://github.com/palantir/python-language-server/issues/515

Do you want to keep the issue open for tracking the work for what you suggested in the last sentence? If not, feel free to close 😉

**Comment by ul** [comment]
I think workaround I proposed is a wrong solution because if language server will ignore snippetSupport and return snippets anyway, and we will filter them out, then it could be that completions left in the list (if any!) are not going to be very useful.

**Comment by ul** [comment]
This workaround https://github.com/autozimu/LanguageClient-neovim/issues/737#issuecomment-465089402 referenced from the upstream bug could be used with kak-lsp:
```
set global lsp_server_configuration python.plugins.jedi_completion.include_params=false
```
(I didn't test it)

**Comment by ul** [comment]
I'm closing this as for this particular case we can't do much except using a workaround. Setting snippetSupport explicitly I think is in the scope of #126

**Comment by FlyingWombat** [comment]
>This workaround autozimu/LanguageClient-neovim#737 (comment) referenced from the upstream bug could be used with kak-lsp:

FYI, tried this and it didn't work for me.  
```
hook global WinCreate .* %{ set global lsp_server_configuration python.plugins.jedi_completion.include_params=false }
```

**Comment by ul** [comment]
Sorry, I did a mistake in the key, it should be
```
set global lsp_server_configuration pyls.plugins.jedi_completion.include_params=false
```
I will update my original comment as well.

**Comment by fominok** [comment]
https://github.com/palantir/python-language-server/pull/529 landed!
