### ISSUE TITLE
Create an option to not use `info` for errors

### ISSUE THREAD

**Issue by ficoos** [ul/kak-lsp#176]
Some servers (e.g. bingo) spew errors all the time if you have auto-hover or auto-reference because those can't be done on keywords.

I want to be able to set up kak-lsp to just log to the debug buffer without using the info feature.

**Comment by ul** [comment]
I could be easily done by overriding `lsp-show-error` command in your kakrc:
```
define-command -override -hidden lsp-show-error -params 1 -docstring "Render error" %{
    echo -debug "kak-lsp:" %arg{1}
}

```
Unfortunately, it's not very well documented, PR with README update or a page in the wiki is more than welcome!

**Comment by ul** [comment]
Did my snippet help? If not, please feel free to re-open the issue.
