### ISSUE TITLE
non-latin symbols cause junk and improper highlighting

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#191]
Here's an example with improper highlighting (with underline):
![image](https://user-images.githubusercontent.com/19470159/55631166-1342e800-57c0-11e9-82cc-cd0bdc2577f3.png)

Here's an example of junk (`M-oM-?M-=`):
![image](https://user-images.githubusercontent.com/19470159/55631297-64eb7280-57c0-11e9-8132-08ed34df7e9f.png)

Possibly related to https://github.com/ul/kak-lsp/issues/170#issuecomment-476136199

**Comment by ul** [comment]
Yes, this is a bug in kak-lsp as Kakoune demands byte offset for highlighter range-specs, but language server sends character offset which kak-lsp just translates to Kakoune's convention without converting to byte position.

**Comment by ul** [comment]
So, the most likely solution will be to convert char offsets to byte offsets in `lsp.kak` when applying new highlighting. As suggested by Franciman@#kakoune we can ask Kakoune to do such conversion, position by position: place cursor to the char (`<line>g<column>l` ???) and use `%val{cursor_column}` to get byte offset.

Any ideas on alternative implementation?

**Comment by andreyorst** [comment]
Using grapheme clusters can't help to convert ranges? It should provide sane ranges for any script.

**Comment by ul** [comment]
This requires access to the content on the kak-lsp server side which we try to avoid. I filed an issue to discuss different approaches: https://github.com/mawww/kakoune/issues/2839

**Comment by andreyorst** [comment]
I've meant to use them applied to the string that is passed to server.
1. kak-lsp passed a string
2. server return range
3. kak-lsp uses grapheme clusters on string to calculate proper size for each letter
4. kak-lsp calculates Kakoune range

**Comment by ul** [comment]
But diagnostics doesn't work that way. Language server reads project files by itself and also uses previously passed buffer contents and then pushes diagnostics to kak-lsp asynchronously. To analyze string in question kak-lsp needs to store buffer content and read files. Which is okay-ish unless we will find a better solution.

**Comment by andreyorst** [comment]
Understood. Sorry, I'm out of Ideas, because I don't know internals of LSP

**Comment by ul** [comment]
I'm almost set on keeping a copy of the buffer on kak-lsp side and using it for analysis. It shouldn't be a that big waste of memory but would allow not to demand extra features from Kakoune.

For the first iteration, I will add support only for UTF-8 buffers.

**Comment by andreyorst** [comment]
Thanks, really appreciate it.

Just curious if, for example, I accidentally open a 1GB file when LSP is active it will cause additional 1GB of RAM usage? I understand that there's no such big source code files, but I often open logs generated by the program I develop, while working with its C++ codebase. Wont it be an issue?

**Comment by ul** [comment]
If there is no language server configured for your 1GB file's filetype then it will not be stored by kak-lsp. It still will be (and _is_ currently as well) sent to kak-lsp if you are using `lsp-enable` instead of more fine-grained `lsp-enable-window` per filetype.

**Comment by andreyorst** [comment]
> If there is no language server configured for your 1GB file's filetype then it will not be stored by kak-lsp. It still will be (and _is_ currently as well) sent to kak-lsp if you are using `lsp-enable` instead of more fine-grained `lsp-enable-window` per filetype.

No, I'm using `lsp-enable-window`. Glad to hear that it won't cause any trouble

**Comment by ul** [comment]
This issues should be resolved by https://github.com/ul/kak-lsp/pull/195
Please let me know if you hit any troubles after upgrade.

**Comment by andreyorst** [comment]
> Please let me know if you hit any troubles after upgrade.

This might be a bit over the top, but it fails. I've f*cked up text with [Zalgo Text Generator](http://www.eeemo.net/):

![image](https://user-images.githubusercontent.com/19470159/60591310-ded2ce00-9da6-11e9-969d-3b3a745b27be.png)

```
q̸̧͇͎͙͎̤̖̗͕̞̯͈͉̲͇̖̙͙̳̀̋̌͛ͯ̃̐ͪ͐͌̀̈͑̋ͥ͒̈́͟ͅw̷̨̛̞̫̯͖̼̭͔̫̖͗ͨ̑̄̎̊͌̇͗̈̾̅ͨ̌͞ͅë́̔̿̋͏̷̻͈͖̞̼͇͈̬̕͜r͉̰̟͖̳͓̹̦̐̔͑ͩ̈̆̑͑͑ͩͮͥ͋ͤ͐̀̕͟ẗ̷̗̱̼̜̟̦̹̤̱͇̘̝̭̗͙̗͕̟ͧ̒ͪ̾͆͜y̛̙̜̘̤̬̻̤̜̠̰̦̞̲̯̼͚ͫ͛͆̈͌͐̊͢ủ̷̧̩̲͈̰͇̖̭̥͕̉̃͐̉ͧͤ͑̑̕i̧͈̳̥̦͉͙̟͓͖͇͚͙̦̩̳͐̑ͫ͑̌ͩ͗̈ͥͮ̚͜͟o̷̽̄̍ͯ̓̂ͫͮͬ͛̇̎ͪͭ̃͌͏̝̣̞̱̖͟͝p̴̥̲̳͈͈͑͆ͤͤ̐͛̽͆ͮ͆͋̃̓ͣ͆̿ͅͅ[̢͙͚̠̙͖͍̥ͧͭ̔̑ͯͯͣ͑̔ͩ̐̅͋̚͘]̸͓̯̫͈̯̜̼̪͖̭͌͌̏͌̃ͨ̑ͥ͆͗͟͢͠a̷̴͖̝͍͕̤̖̗͎̜̖̠̲̔̃̾̉͜͡ͅs̢͓̰̯̝̬̰̞̉ͤ̽̇̾̎̓ͧ̋̀̚͝ͅͅd̶̻͓͕͍̬̟̠͍̻͚̱̩̳̻̓̋̐ͪ́̒̄̄͋̈͌̋ͪ̿̓̆́͢͝ͅf̢͇̘̯͎͚̣̗͉̞̣̺̙̓̑̐̈͋͊ͣ̃̽̚͜g̶̢̛̱̜̝̠̝̥̒̈́͊ͤ͗ͬ̽ͥ̈̽̒̀͝ͅh̴͔͎̞̮̗̭̣͂͌̽͆̇̅ͨ͠͠j̵̥͕̻̦̻̽ͫͣ̋̈́͐͒́̒̀̎ͥͫ̇͊k̷̡̹̫̟͔̺̜̖̫̰̰̣͇̲̑̈́ͭͮͨ̈ͯͮ̈̐̉̊͋̅ͫ͘͞͡l͙̦̤̬̞͉̯ͣ͒̓̏͞͞͝;̨̨͇̬̮̣̮̋̃ͪ͋ͪ̑̐̂́̈͌̅̔͒̾͛͝'̵̧̘̤͔̩̞̤̰̬̐̆̀̃̀͜z̛͎͖̠̘͖͇̓ͮ̃͗ͯ̑ͨ́͠x̶̴͂̎͒ͤͯ̌ͨ͌̄̌̔̿ͣ͝҉̺͇̳̦̥̫̠̹̫̪c̷̵̨̻̙̤̫̞̱̞̙͙̎͂̇̎̈́̽̍͌̋ͪͪ̃̃̄̄̍́̿͝v̵̟̘͈͎̠̘̂̽ͫ̾̓̚̕͢ͅb̴̶͍̲̖̞͔̬̋ͪͨͫ̑ͧ̅͟n̡̡̪̺̲̙͖̙͚̮͑̔ͥ̐̈͑ͧ͐̆͋͐ͯ͌̚͟m̢͇̯̭̩̳̳̩̜̹̺̋̾ͫ̑ͥͦͧ̄͂͗̆̑̅̚̚̕,̨̢͈͕̟̳͖̬͕͖̰̗ͫ̅͋ͧ͗̉̄̓͂͜͠ͅ.̋ͮ̽ͭ͑̋ͬ̎̍̔̏͛̀̐ͣ̀҉̸̶͕̹̰͍͙̤̫̘̺̫̖͈̠͉̱̖/̩̣̗̜̫͈̣̉ͮͣ̅̌͛̇ͪ̏̇͠
```
