### ISSUE TITLE
"info -style menu" appears in docstring popups since 6.2.0

### ISSUE THREAD

**Issue by maximbaz** [ul/kak-lsp#201]
Testing `6.2.0` to release for Arch Linux, I think there's some regression. Or maybe the code in `6.2.0` is for master release of kakoune, not for the latest stable?

In `6.1.0`:

![image](https://user-images.githubusercontent.com/1177900/57580269-cd0c3300-74a7-11e9-89e1-2ac8eef4f8fb.png)

In `6.2.0`:

![image](https://user-images.githubusercontent.com/1177900/57580264-c7165200-74a7-11e9-91c7-172f05a4000b.png)

**Comment by ul** [comment]
Yes, I missed that completions API change wasn't released yet. Not sure what to do the best now.

**Comment by maximbaz** [comment]
Change to "Pre-release" perhaps on Github, we will keep 6.1.0 in Arch repos for now, and let's beg @mawww to cut off a new release of kakoune? 😜

**Comment by ul** [comment]
Good idea, done!

**Comment by maximbaz** [comment]
kakoune `2019.07.01` released, the issue is solved - please remove the "Pre-release" label and close this issue 😉
