### ISSUE TITLE
no method completion in C and Rust

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#202]
## C

At some point there's no more completions for C and Rust method/field syntax like

```c
struct test {
    int data1;
    int data2;
};

int main()
{
    struct test a;
    a.█
}
```
![image](https://user-images.githubusercontent.com/19470159/57697339-a7c02600-765b-11e9-926f-0ff3a158c77d.png)

But if I insert `d` I'll get completions that are marked as fields:

![image](https://user-images.githubusercontent.com/19470159/57697219-67f93e80-765b-11e9-88b9-2131d5b5fba4.png)

I'm using clangd language server (also it's completions are indented with single space in popup for some reason). I believe that the clangd isn't the one who's make this happen, because it works in Emacs eglot, and the same problem happens with RLS.

## Rust
The same with Rust RLS. Sample code:

```rust
struct Test {
    data1: i32,
    data2: i32,
}

fn main() {
    let mut a = Test {
        data1: 2,
        data2: 3,
    };
    a.█
}
```

![image](https://user-images.githubusercontent.com/19470159/57698413-49487700-765e-11e9-8e4e-e71489ddfef9.png)

And again, pressing `d` reveals completions:

![image](https://user-images.githubusercontent.com/19470159/57698501-7006ad80-765e-11e9-9f42-803fef27d9e5.png)

Also doesn't work for namespace syntax:
![image](https://user-images.githubusercontent.com/19470159/57702142-1c985d80-7666-11e9-9ae8-ac696469a9fa.png)

![image](https://user-images.githubusercontent.com/19470159/57702159-26ba5c00-7666-11e9-91a4-fd603c15d2ed.png)

---

I'm using development version of Kakoune, and your plugin is set to master branch. Tell me if more info is needed.

**Comment by andreyorst** [comment]
I've used this `lsp_completion_trigger` regex:

        set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\h\n,=;*(){}\[\]]\z<ret>'"

but disabling it doesn't help.

**Comment by andreyorst** [comment]
kindly pinging @ul

**Comment by ul** [comment]
Sorry, I am drowning in other responsibilities.

I broke it when was improving character offset handling, now should be fixed. Please let me know if it's not.

**Comment by andreyorst** [comment]
It works! Thanks!
