### ISSUE TITLE
"requested by TypeScript but content not available" and very slow diagnostic

### ISSUE THREAD

**Issue by atomrc** [ul/kak-lsp#214]
Hi guys. 

I have been using kak-lsp for quite a while and, I believe, since I started using I noticed that the diagnostic is very slow to run as I type. 
I decided to start investigating this issue recently but I think I need some help from you.

I the `*debug*` buffer, I have a tone of log saying
```
 .../index.d.ts requested by jTypeScript but content not available
```

Everytime I type 1 character I get a tone of those. 

I believe this is the reason for the very slow diagnostic (and the UI blinking all the time as I type). 

I saw this issue appears on Neovim also https://github.com/sourcegraph/javascript-typescript-langserver/issues/432
But I am not sure what to do with this piece of information. 

If it is linked to completion, what kind of expression can I set in the `lsp_completion_trigger` option so that it never triggers? 

Thanks for your help

**Comment by ul** [comment]
Hi, thank you for reporting! I failed to reproduce the problem, would you mind sharing a repo with a sample project?

**Comment by ul** [comment]
Regarding disabling autocompletion, you can do it by setting `lsp_completion_trigger` to `'fail'`

**Comment by atomrc** [comment]
hey @ul thanks for a fast answer.

I tried disabling completion, but it doesn't seem to improve anything. 

Sadly I have had the time to create a small project that reproduce the bug. you can try and clone this one and then edit whatever `.ts` file there is in there (`src/script/util/Logger.ts` might be a good candidate).
https://github.com/wireapp/wire-webapp

**Comment by atomrc** [comment]
So, I switched from `javascript-typescript-langserver` to `typescript-language-server`. 
The diagnostic is not really faster but I don't get the error stacking in the `*debug*` buffer anymore :)

I think I can close this issue now

**Comment by atomrc** [comment]
One question though. Is there a way I can limit the rate at which commands are sent to the server. 
It seems like there is absolutely no debounce, everytime I type a single character the whole file is sent to the language server. 

I cannot seem to find an option that would limit this

**Comment by ul** [comment]
Unfortunately, there is no such option at the moment. Thanks for the idea, I'll consider adding it (and PR is welcome as well!). Meanwhile, you can try wrapping kak-lsp into some script handling debounce.
