### ISSUE TITLE
Fails to initialise with rls

### ISSUE THREAD

**Issue by spacekookie** [ul/kak-lsp#215]
I'm trying to use `kak-lsp` with the `rls` in a setup that I've used on a different computer (and Linux distro) before, but now can't get to work and I'm wondering what might be happening.
My current Linux distro is `NixOS`. The `kak-lsp` config is unchanged from the default that ships with this repository.

Essentially, `kak-lsp` only ever outputs this message: `"kak-lsp: Language server is not initialized, parking request"`. Adding `-v` for verbosity doesn't output any other things from `kak-lsp`

I'm using `kakoune` version `2019.01.20` and `kak-lsp` version `6.2.1`.

My previous setup was using kakoune [`89cd68d`](https://github.com/mawww/kakoune/tree/89cd68d8aff07792b03a0affc19dbb01f036f554) and `kak-lsp` version 86adbabf1aa0cb08c24193e0b1535354bfb9ab56, which works *sometimes*, but not really deterministically.

I'm wondering if you have some ideas about what might be going wrong here and how I can debug this. Thanks!

**Comment by ul** [comment]
It looks like there is a communication broken between kak-lsp client and server (btw, does it work for languages other than Rust?). This thread has some hints on what worth double-checking for troubleshooting that kind of problem: https://discuss.kakoune.com/t/kakoune-with-ubuntu-wsl-windows-platform-to-use-clangd-with-kak-lsp/468

**Comment by spacekookie** [comment]
Hmm...somehow I can't reproduce this issue anymore. I didn't change my `kakoune` or `kak-lsp`, but I did downgrade to Rust 1.34 and now it works (somewhat).

I still can't get a completions dialog to pop-up, even though it should be configured. But considering that this is now an unrelated bug, I think I should close this one.

For anyone finding this in the future, I think Rust `1.35` had some bugs in the `rls`...
