### ISSUE TITLE
No diagnostics and completion on fileopen

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#221]
After opening supported file there's no completion or diagnostics unless kak-lsp is killed from terminal.

OS:  Arch Linux, Fedora 30
Kak-lsp version:
```
$ kak-lsp --version
kak-lsp 6.2.1
```
kakoune-fersion:
```
$ kak -version
Kakoune v2019.07.01-12-gbe3d0f8b
```
Configuration:

    plug "ul/kak-lsp" do %{
        cargo install --force --path . --locked
    } config %{
        define-command lsp-restart %{ lsp-stop; lsp-start }
        set-option global lsp_completion_trigger "execute-keys 'h<a-h><a-k>\S[^\s,=;*(){}\[\]]\z<ret>'"
        set-option global lsp_diagnostic_line_error_sign "!"
        set-option global lsp_diagnostic_line_warning_sign "?"
        hook global WinSetOption filetype=(c|cpp|rust) %{
            map window user "l" ": enter-user-mode lsp<ret>" -docstring "LSP mode"
            lsp-enable-window
            hook -always global KakEnd .* lsp-exit
            lsp-auto-hover-enable
            lsp-auto-hover-insert-mode-disable
            set-option window lsp_hover_anchor true
            set-face window DiagnosticError default+u
            set-face window DiagnosticWarning default+u
        }
        hook global WinSetOption filetype=rust %{
            set-option window lsp_server_configuration rust.clippy_preference="on"
        }
    }

- kak-lsp.toml:
```
verbosity = 0

[server]
# exit session if no requests were received during given period in seconds
# works only in unix sockets mode (-s/--session)
# set to 0 to disable
timeout = 1800 # seconds = 30 minutes

[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
command = "rls"
offset_encoding = "utf-8"
[language.rust.initialization_options]
offsetEncoding = ["utf-8"]

[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_flags.txt", "compile_commands.json"]
command = "clangd"
offset_encoding = "utf-8"
[language.c_cpp.initialization_options]
offsetEncoding = ["utf-8"]
```

**Comment by spacekookie** [comment]
What do you mean with "unless kak-lsp is killed from terminal" ? What does it do then?

**Comment by andreyorst** [comment]
if I do `killall kak-lsp -9` from terminal kak-lsp is restarted and completions and diagnostics start to work

**Comment by spacekookie** [comment]
Oh okay, it's as bizzare as I thought at first. I guess nothing in the logs?

**Comment by andreyorst** [comment]
Can I have quick guide how to get logs out of kak-lsp?

**Comment by ul** [comment]
Thanks for raising this issue, I hit it as well. Producing logs described here https://github.com/ul/kak-lsp/#troubleshooting

However, I realised that some problems are very specific to running kak-lsp daemonized and from Kakoune integration script, I'm going to add an ability to specify the log output file with `--log` option to help analysis of such cases.

**Comment by ul** [comment]
Please try the latest master, I made some changes, and now I don't have a similar problem anymore locally.

**Comment by ul** [comment]
Hmmm, it seems that with typescript language server I still get the problem.

**Comment by andreyorst** [comment]
>Please try the latest master, I made some changes, and now I don't have a similar problem anymore locally.

Sorry I would be able to test only at Monday

**Comment by ul** [comment]
No rush at all, have a nice weekend =)

**Comment by andreyorst** [comment]
It seems that issue is fixed for me
