### ISSUE TITLE
kak-lsp doesn't pickup user config

### ISSUE THREAD

**Issue by vbauerster** [ul/kak-lsp#222]
I noticed that `kak-lsp` doesn't pickup my config at `~/.config/kak-lsp/kak-lsp.toml`.
I've changed `language.go` part to use `gopls` instead of default `bingo`, however `kak-lsp` still launches `bingo` instead of `gopls`. 
Version I use is master 05c8c4b.

**Comment by ul** [comment]
Yes, there is a breaking change in master regarding the config location. Now kak-lsp tries to read `kak-lsp/kak-lsp.toml` under OS-specific config dir as described here https://docs.rs/dirs/2.0.1/dirs/fn.config_dir.html

**Comment by vbauerster** [comment]
Thank you!
