### ISSUE TITLE
`lsp-stop` does nothing

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#228]
calling `lsp-stop` or `lsp-exit` doesn't do anything visible. Completions are still here, diagnostics are displayed too. Hovering works. Some times I want to disable both lsp server and lsp client entirely.

**Comment by ul** [comment]
`lsp-stop` asks kak-lsp server to exit, which does it, but the next kak-lsp request (i.e. triggered by completion) spins up a new kak-lsp session. Hence behaviour you described is expected.

However, I totally agree that something like `lsp-disable` is a desired feature. It should be relatively easy to implement by unregistering `lsp` group of hooks, I'll put it into my queue (but PR is always welcome if you want to give it a go!)

**Comment by supermarin** [comment]
Probably good to close now when #229 is in
