### ISSUE TITLE
Incorrect diagnosings in huge file

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#230]
I've opened big file and deleted 1 letter in function name, but got no error sign, and hover provides old info.

![image](https://user-images.githubusercontent.com/19470159/62303849-8e25c200-b485-11e9-8dc3-db2169b7704f.png)

More than that - If I add empty line with spaces, hover will still show the same info:
![image](https://user-images.githubusercontent.com/19470159/62303956-c0cfba80-b485-11e9-953f-2b69d2bd2408.png)

test file:
[rename me to main.rs please!](https://github.com/ul/kak-lsp/files/3457315/main.txt)

**Comment by occivink** [comment]
Could be related to #245?

**Comment by ul** [comment]
I merged the fix for #245, @andreyorst would you mind validating if it resolves your issue? (It does on my machine with your example).

**Comment by andreyorst** [comment]
It seems to be fixed!
