### ISSUE TITLE
Freezing when encountering cyrillic

### ISSUE THREAD

**Issue by greenfork** [ul/kak-lsp#231]
After minor edits, changing modes or just moving cursor I get "waiting for shell command to finish" quite often to the point where it is easier to disable it.
```
test "can split cyrillic-based words":
  check splitToWords("""
    "Какой сегодня день хороший, однако!" - говорит дед.
    Деду было хорошо..."""
  ) == @["Какой", "сегодня", "день", "хороший", "однако", "говорит", "дед",
         "Деду", "было", "хорошо"]
```

**Comment by ul** [comment]
What is the language server you use? You might need to add `offset_encoding = "utf-8"` to its entry in `kak-lsp.toml`, see https://github.com/ul/kak-lsp/#positioncharacter-interpretation

**Comment by greenfork** [comment]
I'm so ashamed, it's in the manual. I use [nimlsp](https://github.com/PMunch/nimlsp). For now the problem randomly disappeared in either way, with or without `offset_encoding` setting. I will try this solution if the problem arises, thank you very much!

**Comment by ul** [comment]
No reason to be ashamed, glad to hear that kak-lsp works for you! Please don't hesitate to re-open the issue if you will hit this problem again.

BTW, how is nimlsp? I might be back to writing some Nim (for https://github.com/ul/sound-garden), would be nice to do it with some IDEish support this time.

**Comment by SolitudeSF** [comment]
its not the most reliable thing. it doesnt work on some big files. sometimes it provides info only for some symbols. im just used to no-ide-like environment so it doesn't really bother me.
