### ISSUE TITLE
kak-lsp ceased to work suddenly

### ISSUE THREAD

**Issue by vbauerster** [ul/kak-lsp#232]
`kak-lsp` ceased to work, it's strange because it worked yesterday.
Following is `*debug*` buffer:

```
*** This is the debug buffer, where debug info will be written ***
/Users/vbauer/.config/kak/plugins/kak-lsp/rc/lsp.kak:104:11834: 'define-command' inconsistent indentation in the string
plug.kak: Error occured while loading 'ul/kak-lsp' plugin:
          2:6: 'evaluate-commands' 47:2569: 'source' 104:11834: 'define-command' inconsistent indentation in the string
```

**Comment by SolitudeSF** [comment]
probably the cause of this https://github.com/mawww/kakoune/commit/da2f6c296ae3ee280ffaca3937c6ae35c78d1e38

**Comment by vbauerster** [comment]
@SolitudeSF you most probably right, because I've rebuilt kak from master today.

**Comment by SolitudeSF** [comment]
wanted to submit a pr, but i cant see any docstrings that could be triggering this.

**Comment by sjjf** [comment]
I'm seeing this too after updating to the latest kak.

**Comment by ul** [comment]
Thanks, folks, I'm able to reproduce it and will fix today.

However, I'm not sure that inconsistent indentation in a docstring should be penalised, it should be enough just to leave it without indentation trimming. @mawww thoughts?
