### ISSUE TITLE
lsp-stop and lsp-exit commands do not work

### ISSUE THREAD

**Issue by mogenson** [ul/kak-lsp#236]
When using kakoune 2019.07.01 and kak-lsp 6.2.1 from the Arch Linux community repo, the spawned kak-lsp processes stay around after I quit kakoune. Also the lsp-stop and lsp-exit commands do not quit the kak-lsp process when invoked from within a kakoune window.

I'm using the provided kak-lsp.toml language server configuration with the Dart and Rust language servers.

For now I've added `pkill kak-lsp` to a KakEnd hook. But, let me know how I can debug this.

**Comment by ul** [comment]
Sorry for a great confusion with versioning which comes from the fact I don't maintain "snapshot" version, but by 6.2.1 do you mean 6.2.1 release or the latest master (which would output `6.2.1` in the response to `kak-lsp --version` as well)?

In the 6.2.1 I'd expect the problem you described to exist. It's a regression fixed after the release. If you see this behaviour in the latest master, then let's investigate it if you are keen.

**Comment by mogenson** [comment]
I'm using [release 6.2.1](https://github.com/ul/kak-lsp/releases/tag/v6.2.1) as installed as installed by this [Arch Linux package](https://www.archlinux.org/packages/community/x86_64/kak-lsp/) since I was working on a computer without the rust toolchain installed.

I haven't had any issues with the master branch built from source.

Do you know when the next release might be?

**Comment by ul** [comment]
Master has a couple breaking changes, so I had an idea of sneaking another big change (#40) before making the next major version release, but it's blocked by https://github.com/mawww/kakoune/issues/2898.

But because the timeline for it is unclear, now I think I should just cut a release, it's already overdue.

**Comment by ul** [comment]
Argh, it seems I need to resolve #243 first (not sure how many people use pre-compiled releases on FreeBSD but don't want to break it for them)

**Comment by ul** [comment]
https://github.com/ul/kak-lsp/releases/tag/v7.0.0

**Comment by mogenson** [comment]
Thanks!
