### ISSUE TITLE
References

### ISSUE THREAD

**Issue by jacobdufault** [ul/kak-lsp#24]
It'd be great if kak-lsp could show references (`textDocument/references`).

Random feedback: it took me a bit to get kak-lsp running since it requires GNU netcat. Debian seems to only have BSD netcat, so I had to build GNU netcat from source.

**Comment by ul** [comment]
Yes, sounds like a good next feature to add. How do you think it should be done the best? Should it create a scratch buffer with make filetype?

Re: netcat — what the main difference between GNU and BSD versions? We could make options passed to netcat configurable to adapt to distro's default.

**Comment by jacobdufault** [comment]
For netcat, https://www.quora.com/What-is-the-difference-between-the-openBSD-netcat-and-the-GNU-netcat.

For references, up to you. I find the grep approach very handy, as you can easily edit it.

**Comment by ul** [comment]
I haven't found any difference which should affect kak-lsp neither by this link nor by googling. How exactly was it failing in your case?

One of the options to mitigate this issue is to add support for sending requests to kak-lsp itself: #25

**Comment by jacobdufault** [comment]
The believe the port and the `-c` cause issues.
