### ISSUE TITLE
Separate diagnostics and hover information

### ISSUE THREAD

**Issue by Vurich** [ul/kak-lsp#240]
Currently, diagnostics are printed underneath the hover contents. This is frustrating because I usually want to have a limit on the size of the hover information but that means that I can never see the diagnostics if my cursor is over a documented item. I think ideally there would be a toggle for which takes precedence, and an option for "neither", which would act like the current behaviour. This would probably be a `lsp-hover-precedence` option with possible elements `'diagnostics'`, `'hover'`, `''`, defaulting to `''`, which would then be sent to `kak-lsp`. A command to toggle the preference could be written by a user as long as `kak-lsp` supports it.

**Comment by ul** [comment]
That's a good idea! In terms of implementation, I'm thinking about having `lsp-show-hover` to receive hover content and diagnostics as two separate params, so the user can override the command and customize rendering.

**Comment by Vurich** [comment]
I have a branch that implements this here https://github.com/ul/kak-lsp/compare/cb394ad16b3dd5d4f6bc63aef679a57e158e9c66...Vurich:master, but it uses one of my crates in order to do the quoting lazily. I would understand if you don't want to roll that change into this one.

**Comment by ul** [comment]
I don't think quoting is a bottleneck in kak-lsp, but care about performance is highly appreciated. I'm keen to use `lazy-string-replace`, though it worth providing measurements to ensure optimisation happened (kak-lsp would greatly benefit from a few `criterion` benches!).

Your implementation is leaning towards "option-driven" solution. How do you think, will be an alternative below more in "Kakoune spirit"? I propose to replace `lsp-show-hover` implementation with the following:

```diff
-define-command -hidden lsp-show-hover -params 2 -docstring "Render hover info" %{ evaluate-commands %sh{
+define-command -hidden lsp-show-hover -params 3 -docstring %{
+lsp-show-hover <anchor> <info> <diagnostics>
+Render hover info.
+} %{ evaluate-commands %sh{
-   content=$2
+   # TODO strip leading whitespaces when $2 is empty
+   content=$(printf '%s\n\n%s' $2 $3)

    if [ $kak_opt_lsp_hover_max_lines -gt 0 ]; then
        content=$(printf %s "$2" | head -n $kak_opt_lsp_hover_max_lines)
    fi

    content=$(printf %s "$content" | sed s/\'/\'\'/g)

    case $kak_opt_lsp_hover_anchor in
        true) printf "info -anchor %%arg{1} '%s'" "$content";;
        *)    printf "info '%s'" "$content";;
    esac
}}
```

and pass info and diagnostics separately from Rust side:

```diff
-    let command = if diagnostics.is_empty() {
-        format!(
-            "lsp-show-hover {} {}",
-            params.position,
-            editor_quote(&contents)
-        )
-    } else if contents.is_empty() {
-        format!(
-            "lsp-show-hover {} {}",
-            params.position,
-            editor_quote(&diagnostics)
-        )
-    } else {
-        let info = format!("{}\n\n{}", contents, diagnostics);
-        format!("lsp-show-hover {} {}", params.position, editor_quote(&info))
-    };
+    let command = format!(
+        "lsp-show-hover {} {} {}",
+        params.position,
+        editor_quote(&contents),
+        editor_quote(&diagnostics)
+    );
```

This way anyone will be able to use `define-command -override lsp-show-hover` in their `kakrc` to customize behaviour according to one of 4 options, or invent their own.

In some sense it's less user-friendly for the 4 basic options but more flexible and keeps kak-lsp implementation cleaner.

What do you (and anyone watching this issue) think?

**Comment by danr** [comment]
>>> This way anyone will be able to use define-command -override lsp-show-hover in their kakrc to customize behaviour according to one of 4 options, or invent their own.

I think this is great: a good default that works out of the box that can be customized on demand. Overriding a def is a nice way to customize this. 

How does this relate to signature help? Is it possible to customize that in the same way?

**Comment by ul** [comment]
> How does this relate to signature help? Is it possible to customise that in the same way?

It is possible to override `lsp-show-signature-help`, which takes the position it was requested at as the first argument (it is ignored in the default implementation, but could be useful in a custom one) and signature label as the second (which is `echo`ed in the default implementation).

It is not very well documented, but Kakoune part of response handling (mostly `lsp-show-*` commands) is designed with overrides in mind. It probably just needs better docstrings and mention in the README.

**Comment by Vurich** [comment]
The design using an override is a good one, but I think that the `content = $(printf ...)` line should be somehow extracted to its own configurable setting, since that's by far the part that users will be most likely to want to change.

**Comment by ul** [comment]
`set-option global lsp_show_hover_format 'printf %s "${lsp_info}"'` would make kak-lsp to show only hover response, without diagnostics.
