### ISSUE TITLE
clangd define expansion doesn't display correctly

### ISSUE THREAD

**Issue by andreyorst** [ul/kak-lsp#249]
when hovering over call to this macro:
![image](https://user-images.githubusercontent.com/19470159/66830620-92c72600-ef5e-11e9-88f1-0a5645267292.png)
the info box is truncated:
![image](https://user-images.githubusercontent.com/19470159/66830605-893dbe00-ef5e-11e9-81ed-0024b47ef470.png)
when using `set window lsp_hover_anchor true` it's more truncated:
![image](https://user-images.githubusercontent.com/19470159/66830749-e6d20a80-ef5e-11e9-99b9-0d71594bb038.png)

**Comment by Delapouite** [comment]
I think this is related to https://github.com/mawww/kakoune/issues/2237

**Comment by andreyorst** [comment]
ah, it seems so
