### ISSUE TITLE
auto highlight occurs when cursor is not on the word

### ISSUE THREAD

**Issue by vbauerster** [ul/kak-lsp#252]
I use `kak-lsp` with `lsp_auto_highlight_references` on. I have noticed that it still highlights the word when cursor position is over right side adjacent to the word:

[![z.png](https://i.postimg.cc/PJnV2FQs/z.png)](https://postimg.cc/xJgPd5Zt)

Technically cursor is not on the word, so I think it should not be highlighted.

**Comment by ul** [comment]
As far as I can tell this behaviour is specific to RLS, not kak-lsp. Might worth raising a bug there (worth noting that we use textDocument/references for this feature, not textDocument/documentHighlight at the moment).
