### ISSUE TITLE
Change dart lsp server

### ISSUE THREAD

**Issue by dcov** [ul/kak-lsp#254]
Hello,

It appears that the dart-sdk now ships its own lsp analysis server so the [current option](https://github.com/natebosch/dart_language_server) has become obsolete. The new command is something like:
```bash
dart path/to/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp
```
I tried to get it working on my machine but since I'm relatively new to kakoune in general, I've had no luck. I tried aliasing it to `dart_language_server` and deactivated the old command, but it didn't seem to work. Any help would be appreciated.

Thanks.

**Comment by mogenson** [comment]
`kak-lsp` interprets the entire string as one command. Use the `args` item as follows (with correct dart-sdk path):

```
[language.dart]
filetypes = ["dart"]
roots = ["pubspec.yaml", ".git"]
command = "dart"
args = ["/opt/dart-sdk/bin/snapshots/analysis_server.dart.snapshot", "--lsp"]
```

Works for me with kakoune 2019.12.10, kak-lsp 7.0.0, Dart 2.7.0.

**Comment by ul** [comment]
Hey folks, if the new server works then is anyone keen to submit PR with the update to the default config? The only thing which bothers me is that you should specify the path to Dart SDK which means that for many users it won't work out-of-the-box.

**Comment by mogenson** [comment]
Is anything from the TOML config file expanced before being run?

Could I format a command like: `dart $(which dart)/../snapshots/analysis_server.dart.snapshot --lsp` ?

**Comment by topisani** [comment]
No, but that could be done by setting the command to `sh` and args to `['-c', 'dart ... ']`

**Comment by mogenson** [comment]
Good idea. But, I think I might be losing the `-c` argument to `sh` somewhere.

I defined my language server as:
```
[language.dart]
filetypes = ["dart"]
roots = ["pubspec.yaml", ".git"]
command = "sh"
args = ["-c", '"dart $(dirname $(which dart))/snapshots/analysis_server.dart.snapshot --lsp"']
```

With single quotes around the `dart ...` to pass the string as one argument to the `sh` command, and inner double quotes to allow `sh` to expand the `$()` subshells.

The log from `kak-lsp` shows the literal string, then an error where `sh` is treating `dart /opt/flutter/...` as a path and can't find it.

```
Jan 30 10:14:02.749 INFO Starting Language server `sh -c "dart $(dirname $(which dart))/snapshots/analysis_server.dart.snapshot --lsp"`, module: kak_lsp::language_server_transport:21
Jan 30 10:14:02.754 ERRO Language server error: sh: dart /opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp: No such file or directory
```

If we try these out manually in a shell, the following work:
```
sh -c "dart $(dirname $(which dart))/snapshots/analysis_server.dart.snapshot --lsp"
sh -c "dart /opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp"
```

However, the following produces the error from above:
```
sh "dart $(dirname $(which dart))/snapshots/analysis_server.dart.snapshot --lsp"
     sh: dart /opt/flutter/bin/cache/dart-sdk/bin/snapshots/analysis_server.dart.snapshot --lsp: No such file or directory
```

It seems like the `-c` argument is being lost somewhere.

**Comment by topisani** [comment]
no, the quoting is the mistake. It is being passed as a separate arg because it is a separate item in the list, so what you're doing is the same as `sh -c '"dart ..."'`. Remove the quotes, and it should work

**Comment by mogenson** [comment]
Thanks! PR incoming.

**Comment by dcov** [comment]
Sorry for the late reply, and for the late close.

Thanks for the fix @mogenson
