### ISSUE TITLE
Windows prebuilts

### ISSUE THREAD

**Issue by jacobdufault** [ul/kak-lsp#26]
It'd be great to have prebuilts available for windows as well.

I'm investigating using kak-lsp as part of cquery e2e testing - ideally CI can just download the prebuilt (cquery CI runs on windows, macos, and linux).

**Comment by ul** [comment]
Here you go: https://github.com/ul/kak-lsp/releases/tag/v3.1.4

Hope kak-lsp will work fine on Windows (I haven't tested it), let me know if you hit platform-specific problems.

Also we could continue discussion in #15 to come up with specific steps to support your use-case better.
