### ISSUE TITLE
v7.0.0 completion not working

### ISSUE THREAD

**Issue by aecepoglu** [ul/kak-lsp#263]
I have just downgraded from 7.0.0 to 6.2.1 to get my completions working.

Given the config:

```
[server]
[language.ocaml]
filetypes = ["ocaml"]
roots = ["Makefile", "dune-project", ".git"]
command = "ocamlmerlin-lsp"

[language.javascript]
filetypes = ["javascript"]
roots = ["package.json"]
command = "javascript-typescript-stdio"
```

1. I found that with OCaml, the completions were falling behind (To get completion for `MyModule.foo`, I had to type `MyModule.x` and then delete `x`).

2. With JavaScript I had the server crashing on me regularly

I would like to ask if issues regarding completion suggestions are known and accepted. I looked at past issues and I've seen a couple regarding zero-length but this seemed different.

If such issues are not know, then I will go back to v7.0.0 and provide you with some logs

**Comment by ul** [comment]
Thanks for reporting it. No, that kind of issues with completion are not known or accepted. Logs would be helpful, as well as testing with the latest master. If it has this problem fixed then I should cut a release probably.

**Comment by pickfire** [comment]
Is this still in v8?

**Comment by aecepoglu** [comment]
On "7.0.0-snapshot" I feel fine.
