### ISSUE TITLE
Did anybody manage to get tsserver working?

### ISSUE THREAD

**Issue by Vincent-Carrier** [ul/kak-lsp#274]
I've tried a bunch of different things, but I always get the same error:

```
Dec 31 17:00:14.293 DEBG To server: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"colorProvider":null,"completion":{"completionItem":{"documentationFormat":["plaintext"],"snippetSupport":false}}},"workspace":{"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"]}}},"processId":42082,"rootUri":"file:///Users/vincent/lighthouse/w4/d5","trace":"off"},"id":0}, module: kak_lsp::language_server_transport:175
Dec 31 17:00:14.596 DEBG From server: {"seq":0,"type":"response","command":"unknown","request_seq":0,"success":false,"message":"Error processing request. Unexpected token C in JSON at position 0\nSyntaxError: Unexpected token C in JSON at position 0\n    at JSON.parse (<anonymous>)\n    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:140952:36)\n    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:142270:27)\n    at Interface.emit (events.js:203:13)\n    at Interface._onLine (readline.js:314:10)\n    at Interface._normalWrite (readline.js:459:12)\n    at Socket.ondata (readline.js:170:10)\n    at Socket.emit (events.js:203:13)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:210:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)"}
, module: kak_lsp::language_server_transport:149
Dec 31 17:00:14.596 ERRO Invalid call from language server: Null, module: kak_lsp::controller:108
Dec 31 17:00:14.596 DEBG From server: {"seq":0,"type":"response","command":"unknown","request_seq":0,"success":false,"message":"Error processing request. Unexpected end of JSON input\nSyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at IOSession.Session.onMessage (/usr/local/lib/node_modules/typescript/lib/tsserver.js:140952:36)\n    at Interface.<anonymous> (/usr/local/lib/node_modules/typescript/lib/tsserver.js:142270:27)\n    at Interface.emit (events.js:203:13)\n    at Interface._onLine (readline.js:314:10)\n    at Interface._normalWrite (readline.js:459:12)\n    at Socket.ondata (readline.js:170:10)\n    at Socket.emit (events.js:203:13)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:275:11)\n    at Socket.Readable.push (_stream_readable.js:210:10)\n    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)"}
, module: kak_lsp::language_server_transport:149
Dec 31 17:00:14.596 ERRO Invalid call from language server: Null, module: kak_lsp::controller:108
Dec 31 17:00:14.597 DEBG From server: {"seq":0,"type":"event","event":"typingsInstallerPid","body":{"pid":42119}}
```

Any help is appreciated! :)

**Comment by danr** [comment]
Ironically tsserver is not a language server (it has its own protocol). For TypeScript you can try the language servers https://github.com/theia-ide/typescript-language-server and https://github.com/sourcegraph/javascript-typescript-langserver.

**Comment by schemar** [comment]
Are there any plans to support `tsserver` in addition to the other language servers? Like [Ale](https://github.com/dense-analysis/ale) does for vim?

Both TypeScript language server implementations mentioned above are severely lacking. For example:

- https://github.com/theia-ide/typescript-language-server doesn't understand TSX at all
- https://github.com/sourcegraph/javascript-typescript-langserver doesn't understand advanced types like `Omit<...`

I know it is not your fault that these language servers suck. Still, it would be nice to have `tsserver` support. Though I have no idea how much effort an implementation would be.

**Comment by ul** [comment]
I'm not sure if the current kak-lsp architecture is flexible enough to accommodate support for a different protocol but I'd say that PR is welcome if you are willing to try.

kak-lsp is aimed to bring IDE-like convenience to Kakoune in the first place, not be a reference LSP implementation or something like that. If something is orthogonal and could stay separate then it's good but if pragmatically it benefits from extending kak-lsp, why not?

**Comment by danr** [comment]
Theia's TS langserver actually does support tsx but you have to configure kak-lsp like so:

```toml
[language.tsx]
filetypes = ["typescript"]
roots = ["package.json"]
offset_encoding = "utf-8"
command = "typescript-language-server"
args = ['--stdio']
```

From the discussion on https://github.com/ul/kak-lsp/issues/211

**Comment by schemar** [comment]
Thanks, @danr , that helped a lot.
@ul it seems Ale has a lot of `if (tsserver) {} else {}` parts in its code, which would probably be a lot of work and not necessarily the maintainable thing to do in kak-lsp.
If someone wanted to add support for tsserver, I could imagine the first step would be to extract all calls to the LSP behind an interface which could then be implemented by tsserver. What do you think?
If you point me in the right directions, I could give the creation of such an interface a shot.

**Comment by ul** [comment]
You can start with https://github.com/theia-ide/typescript-language-server, which is a wrapper around `tsserver`, and then add custom LSP methods to support functionality you are missing. It's fairly straightforward to add calls to those bespoke methods in kak-lsp, we already have plenty of them (introduced by ccls, cquery and eclipse-jdt language servers).

**Comment by schemar** [comment]
Yeah, adding tsserver support to kak-lsp would be a huge task. For example, kak-lsp has jsonrpc hard coded in many places and tsserver *also* doesn't speak jsonrpc. And then in addition to that, you would need to check everywhere which (de)serialization to do based on the running server.
Unfortunately, https://github.com/theia-ide/typescript-language-server is currently unmaintained. Last PR was merged in October and that is also the last commit.

Well, maybe one day tsserver will speak lsp. So long, I will need to stay buggy, I guess 😅 Maybe I find a fork that fixes the most annoying thing: when I move the cursor over an `undefined`, I get an error message covering the whole screen, see below.

Thank you for all your support and detailed answers (and kak-lsp in the first place).

![grafik](https://user-images.githubusercontent.com/1196244/80804758-67ccb880-8bb6-11ea-91d2-6c538a465329.png)

**Comment by DrSensor** [comment]
Good news! Support for LSP protocol has been included in [TypeScript 4.3 Iteration Plan](https://github.com/microsoft/TypeScript/issues/42762).

https://github.com/microsoft/TypeScript/issues/39459#issuecomment-696179304

**Comment by danr** [comment]
Great! That's a relief.

**Comment by Vincent-Carrier** [comment]
Nice! In the meantime, I’ve had some success with Deno’s LSP implementation. 🙂
