### ISSUE TITLE
Any plan for supporting textDocument/implementation?

### ISSUE THREAD

**Issue by tw4452852** [ul/kak-lsp#277]
Hi there,

I like this LSP client, but it seems lacks [textDocument/implementation](https://microsoft.github.io/language-server-protocol/specification#textDocument_implementation), any plan for that?

**Comment by ul** [comment]
Done. `lsp-implementation` UX is similar to `lsp-references` except no default goto binding. Please let me know if you hit any problems.

**Comment by tw4452852** [comment]
Thanks @ul . 
It works like a charm!
