### ISSUE TITLE
go to references shows an empty buffer

### ISSUE THREAD

**Issue by Amanita-muscaria** [ul/kak-lsp#278]
I'm working on the nushell codebase (based on SHA: e76c0788). When I use `gr` or `lsp-references` it just brings up an empty buffer with no references in it. I figured it could be spinning waiting for rls to respond but after waiting for a while it was still empty.

**Comment by ul** [comment]
I was unable to checkout ref you mentioned, so I tested on the d29fe6f6 which was a master head at the moment. And indeed go to references opens an empty buffer. At the same time, it works flawlessly on kak-lsp codebase. Thanks for reporting, I'll investigate it.

**Comment by ul** [comment]
RLS returns an empty response. The problem is not specific to kak-lsp, I managed to reproduce it using VS Code + Rust (rls) extension. I might worth reporting it to RLS team.
