### ISSUE TITLE
Lots of "content modified" errors with ra_lsp_server.

### ISSUE THREAD

**Issue by jneem** [ul/kak-lsp#285]
I'm using ra_lsp_server from the rust-analyzer project. It works well, but has the tendency to show lots of messages saying "rust language server error: 'content modified'". According to the lsp thread [here](https://github.com/microsoft/language-server-protocol/issues/584#issuecomment-448671014), clients should respond to "ContentModified" errors by just dropping or retrying the request.

If you think it's the right solution, I think I can manage a PR that just drops ContentModified errors.

**Comment by ul** [comment]
Yes, I think it's a reasonable strategy to implement, thank you for handling it.

**Comment by ul** [comment]
Fixed in https://github.com/ul/kak-lsp/pull/286
