### ISSUE TITLE
rust-analyzer support?

### ISSUE THREAD

**Issue by dpc** [ul/kak-lsp#292]
I heard that `rust-analyzer` is getting better and better, and I wonder - how could I try it with `kak-lsp`?

**Comment by ul** [comment]
Once you installed `ra_lsp_server` (https://github.com/rust-analyzer/rust-analyzer/releases), just edit your `kak-lsp.toml` config and restart kak-lsp:

```diff
[language.rust]
filetypes = ["rust"]
roots = ["Cargo.toml"]
-command = "rls"
+command = "ra_lsp_server"
```

**Comment by dpc** [comment]
At least in current master branch the `command` has to be `command = "rust-analyzer"`, it seems. Otherwise - worked for me. Thank you!
