### ISSUE TITLE
pyls.configurationSource=["flake8"] not working

### ISSUE THREAD

**Issue by Invarianz** [ul/kak-lsp#296]
I just tried to use the flake8 linter on my python code together with kak-lsp.
I followed the advice in the wiki and did **not** do a configuration via the kak-lsp.toml file but put the following into my `WinSetOption` block.
```
set global lsp_server_configuration pyls.configurationSources=["flake8"]
```

The full block with the kak-lsp initalization reads:
```
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(dart|latex|python|c|cpp) %{
    lsp-enable-window
    set global lsp_hover_anchor true
    set global lsp_auto_highlight_references true
    ## pyls does not accept options via kak-lsp.toml
    set global lsp_server_configuration pyls.configurationSources=["flake8"]
}
```
The option is clearly used but `flake8` never started with the following debug output:
```
*** This is the debug buffer, where debug info will be written ***
Config-change detected:
Config-change detected: pyls.configurationSources=["flake8"]
kak-lsp: Language server is not initialized, parking request
```
However, I can check in my running processes that `pyls` is actually running and using the standard linters/error checkers.

It is unclear to me if this error is related to [Issue 215](https://github.com/ul/kak-lsp/issues/215) and [Issue 155](https://github.com/ul/kak-lsp/issues/155)

**Comment by Phlogistique** [comment]
I think that this is pyls working as intended: `configurationSource` tells pyls to find the configuration in the `[flake8]` section of your `setup.cfg`, or in your `flake8.cfg`; but that does not mean that it will run flake8.

If you want pyls to run flake8, you will need to install a separate plugin. See https://github.com/palantir/python-language-server/issues/190

**Comment by Invarianz** [comment]
Thanks for the info. This is then definitely not a problem with `kak-lsp` but the design decisions of `pyls`. I will mark this as closed.
