### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by FrankAtto** [ul/kak-lsp#309]
Hello,
would it be possible to release a new version?
I would like to use kakoune-lsp for my studies but the old golang server (bingo) causes some problems that are fixed with gopls in vscode.
There was a commit that changed to gopls shortly after the newest release.
Thanks for the great project!

Edit: I just tried master and that seems to fix a rust bug as well that i thought was caused by something different. But i would prefer if i could continue to use my offical distribution package.

**Comment by ul** [comment]
Thank you for a nudge, the next release is indeed overdue. I was hoping on squeezing a few more breaking changes but never got time to work on them. I'll cut a new release now.
