### ISSUE TITLE
Noob trying to make kak-lsp work

### ISSUE THREAD

**Issue by filipeisho** [ul/kak-lsp#312]
Hi, sorry for the dumb question but I have been hitting my head hard against this... 
I am trying to setup kak-lsp for ruby (which I saw it was already supported) but I can't seem to make it work. I installed kak-lsp, I installed solargraph (a language server for ruby), I checked the kak-lsp.toml (and the ruby block was there) and I wrote

```
hook global WinSetOption filetype=(ruby|python|go|javascript|typescript|c|cpp) %{
        lsp-enable-window
}
```

 in the kakrc... The problem is I see no errors in the debug buffer. Everything appears to work but I have no autocompletion or go to definition or anything. I tried installing from source and installing kak-lsp using plug.kak.. Can someone please tell me what I am missing here?

**Comment by ul** [comment]
Hello, have you checked kak-lsp logs? There could be some clues. See https://github.com/ul/kak-lsp#troubleshooting on how to turn logs on.

**Comment by filipeisho** [comment]
Thanks, that worked! The log:

`Apr 24 11:50:55.445 INFO Starting main event loop, module: kak_lsp::session:29
Apr 24 11:50:55.467 DEBG Language server is not configured for filetype `ruby`, module: kak_lsp::session:80
Apr 24 11:50:56.866 DEBG From editor: `

Does this mean kak-lsp is not reading the kak-lsp.toml?

**Comment by filipeisho** [comment]
Sorry to bother, again..
Now I got the autocompletion working but I don't seem to understand how the other features work. I tried the go to definition without success

**Comment by ul** [comment]
Would you mind posting relevant part of the kak-lsp logs? This way we can pinpoint if it fails to communicate to the language server, or language server gives an empty response, or kak-lsp fails to make editor jump.

**Comment by filipeisho** [comment]
I didn't post any logs because there weren't any after `kak-lsp: Language server is not initialized, parking request`... Probably I am doing something wrong, just to be sure, the go to definition feature works by highlighting the method's name, pressing gd and then it should go to where the method is defined, right?

**Comment by ul** [comment]
That's right. If you see `kak-lsp: Language server is not initialized, parking request` it means that kak-lsp daemon is running and your request from Kakoune reached it. But something went wrong after starting the language server: it never came back with `initialized` response.

**Comment by filipeisho** [comment]
Okay I am following again the troubleshooting guide and I am running kak-lsp with an arbitrary session id and kakoune with that session id after that. Everything seems to be working. As I said the gd doesn't work and the gr goes to an empty buffer. This are the logs after opening, doing gd, doing gr and closing kak:
`
May 07 14:28:58.964 INFO Starting main event loop, module: kak_lsp::session:29
May 07 14:29:04.531 INFO Starting Language server `solargraph stdio`, module: kak_lsp::language_server_transport:21
May 07 14:29:31.955 INFO Shutting down language servers and exiting, module: kak_lsp::session:180
May 07 14:29:31.955 INFO Exit ruby in project /Users/filipeisho/bigbang, module: kak_lsp::session:185
May 07 14:29:31.955 INFO Waiting for Controller to finish..., module: kak_lsp::thread_worker:18
May 07 14:29:31.956 INFO Waiting for Messages to language server to finish..., module: kak_lsp::thread_worker:18
May 07 14:29:32.059 ERRO Language server error: Solargraph is listening on stdio PID=2377
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.5-compliant syntax, but you are running 2.6.0.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
[ANY] Solargraph initialized (4.840564999962226 seconds)
, module: kak_lsp::language_server_transport:52
May 07 14:29:32.956 INFO ... Messages to language server terminated with ok, module: kak_lsp::thread_worker:20
May 07 14:29:32.956 INFO Waiting for Messages from language server to finish..., module: kak_lsp::thread_worker:18
May 07 14:29:32.956 INFO ... Messages from language server terminated with ok, module: kak_lsp::thread_worker:20
May 07 14:29:32.956 INFO Waiting for Language server errors to finish..., module: kak_lsp::thread_worker:18
May 07 14:29:32.956 INFO ... Language server errors terminated with ok, module: kak_lsp::thread_worker:20
May 07 14:29:32.957 INFO ... Controller terminated with ok, module: kak_lsp::thread_worker:20
May 07 14:29:32.957 INFO Waiting for Messages to editor to finish..., module: kak_lsp::thread_worker:18
May 07 14:29:32.957 INFO ... Messages to editor terminated with ok, module: kak_lsp::thread_worker:20`

**Comment by filipeisho** [comment]
Ok I finally got it working by reinstalling solargraph. Now hover,gd,gr works. Last question before I close this issue, what do I need to put in my kakrc to enable automatic hovering? I was trying
`hook global WinSetOption filetype=(ruby|vue|python|typescript|go|javascript|c|cpp) %{
        lsp-enable-window
        lsp-enable-auto-hover
}`
