### ISSUE TITLE
Javascript/Typescript doesn't work with EPERM error

### ISSUE THREAD

**Issue by minhtrietbkit** [ul/kak-lsp#313]
## Environment

1. MacOS
2. NodeJS 10
3. Use LSP server https://github.com/sourcegraph/javascript-typescript-langserver

## Configs

1. `kakrc`

```
# omitted other parts
# Enable LSP support
#

eval %sh{kak-lsp --kakoune -s $kak_session --config ~/.config/kak/lsp/kak-lsp.toml}

hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
        lsp-enable-window
}
```

`kak-lsp.toml`

```
[language.javascript]
filetypes = ["javascript"]
roots = ["package.json", "tsconfig.json"]
command = "javascript-typescript-stdio"
```

2. Reproduce

1. Create a *.js file: `touch temp.js`
2. Open that file with kak: kak temp.js
3. Start coding js

## Behaviour

1. Clipper says Language server is not initialized, parking request

![image](https://user-images.githubusercontent.com/31511019/80332106-e07af000-8817-11ea-89c0-76fa4d4e007e.png)

2. After a while, clipper says javascript language server error: 'EPERM: operation no permitted, scandir ''/Users/username/Libarary/Cookies'''

![image](https://user-images.githubusercontent.com/31511019/80332314-875f8c00-8818-11ea-87d6-eb0d22bd4c4f.png)

## kak-lsp troubleshooting mode log

```
Apr 26 23:47:25.647 INFO Starting main event loop, module: kak_lsp::session:29           
Apr 26 23:47:34.066 INFO Starting Language server `flow lsp`, module: kak_lsp::language_s
erver_transport:21                          
thread 'Controller' panicked at 'Failed to start language server: Os { code: 2, kind: Not
Found, message: "No such file or directory" }', src/language_server_transport.rs:22:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Apr 26 23:47:35.850 INFO Waiting for Controller to finish...thread 'main' panicked at 'Bo
x<Any>, ', src/thread_worker.rsmodule::29 kak_lsp::thread_worker:18
Apr 26 23:47:35.850: 17                                                                  
INFO ... Controller terminated with err, module: kak_lsp::thread_worker:20
Apr 26 23:47:35.850 INFO Waiting for Messages to editor to finish..., module: kak_lsp::th
read_worker:18                              
Apr 26 23:47:35.850 INFO ... Messages to editor terminated with ok, module: kak_lsp::thre
ad_worker:20
```

**Comment by ul** [comment]
Most likely there is no project root marker (`package.json` or `tsconfig.json` file) all the way up from `temp.js` which makes kak-lsp to walk up to filesystem root and report it as a workspace root to the language server. In its turn, the language server starts to scan files in that misleading workspace and eventually hits protected user directories which makes Catalina upset and it denies access for the language server which throws the error you see.

**Comment by minhtrietbkit** [comment]
Thank you, the analysis makes sense. Adding the package.json file works. 

Here's a little question, not a bug per se: the initializing process takes quite long - around 20s - 30s. Is it normal or did I do something wrong?

**Comment by ul** [comment]
I don't have much experience with `javascript-typescript-server` (I use Flow at work and have almost no active JS hobby projects) but 20 seconds sounds like the way too long for an empty project (just tried, it initializes quickly on my machine). If you are talking about a large project then I can imagine that it could take some time for the language server to parse `node_modules` content and the timing you mentioned is not that surprising.

**Comment by minhtrietbkit** [comment]
Thanks for your effort!
