### ISSUE TITLE
Support custom action rust-analyzer.applySourceChange

### ISSUE THREAD

**Issue by juniperkiwi** [ul/kak-lsp#314]
Right now, rust-analyzer implements either the majority of or all of its code actions using a custom command, rust-analyzer.applySourceChange. I'd like to be able to use rust-analyzer's code actions, and to that end, I'd like to add support to kak-lsp for this custom action.

Currently, trying to execute code actions just results in "workspace/executeCommand not supported".

See https://github.com/rust-analyzer/rust-analyzer/issues/1232 for some discussion of this issue, and https://github.com/microsoft/language-server-protocol/issues/724 for rust-analyzer's rationale for not using standard tools for LSP code actions.

I couldn't find any documentation for the command's arguments, but the following snippets implement parsing it:
- official plugin in JS: https://github.com/rust-analyzer/rust-analyzer/blob/7a9ba1657daa9fd90c639dcd937da11b4f526675/editors/code/src/source_change.ts
- neovim language client in Rust: https://github.com/autozimu/LanguageClient-neovim/blob/18434f2cd9abc33498e705dfde70d80e19223d0f/src/types.rs#L1152-L1156 / https://github.com/autozimu/LanguageClient-neovim/blob/18434f2cd9abc33498e705dfde70d80e19223d0f/src/language_server_protocol.rs#L978-L1008

Would this be something kak-lsp would be OK with supporting?

**Comment by ul** [comment]
Yes, kak-lsp is open to custom LSP methods. We already have a few of them for ccls, clangd and eclipse-jdt specific functionality.
