### ISSUE TITLE
lsp-format messes up multibyte chars in go source

### ISSUE THREAD

**Issue by voroskoi** [ul/kak-lsp#316]
Hi,

I have a go file with the following line in it:
```
var accents = []rune{'í','é','á','ű','ő','ú','ö','ü','ó'}
```

Running lsp-format on this file gives the following output:
```
var accents = []rune{'Ã­' ,'Ã© ','Ã ¡',' Å±', 'Å' ,'Ãº ','Ã ¶','Ã¼','Ã³'}
```

Running v8.0.0. Thanks.

**Comment by ul** [comment]
Hello! How does `[language.go]` section in your `kak-lsp.tom` look like? You might need to add (or remove) `offset_encoding = "utf-8"` to/from it. https://github.com/ul/kak-lsp#encoding

**Comment by voroskoi** [comment]
Thanks for Your feedback! Sorry for the late reply.

I have changed my main machine since the report and I could not even reproduce the error on it.
Now i finally was able to test this with the original system, but had no luck with reproducing it.

I think it is safe to assume it is fixed now. Closing.
