### ISSUE TITLE
error while trying tor run code actions

### ISSUE THREAD

**Issue by vbauerster** [ul/kak-lsp#328]
Whenever there are code actions available I try to run one, but got following error:

```
Error: 1:1: 'lsp-execute-command' 2:5: 'lsp-did-change-and-then' 1:2: 'try' 2:5: 'evaluate-commands' 1:1: 'lsp-execute-command-request' wrong argument count
```

This happens with both `rls` and `rust-analyzer`.

**Comment by topisani** [comment]
I've been getting this recently as well with flutter/dart

**Comment by WeCodingNow** [comment]
Can confirm, getting the same error in typescript files on trying to import something with code actions.

![image](https://user-images.githubusercontent.com/9677869/83559286-05503a80-a51d-11ea-9378-19bb69339194.png)
![image](https://user-images.githubusercontent.com/9677869/83559310-0da87580-a51d-11ea-8ef1-8efef9b5d308.png)
![image](https://user-images.githubusercontent.com/9677869/83559342-17ca7400-a51d-11ea-8f83-a51a6d46e929.png)

repo: https://github.com/WeCodingNow/AIS_SUG_frontend
file: src/store/types.ts
typescript language server: that one that you install with npm -g install typescript typescript-language-server
