### ISSUE TITLE
&nbsp; in info for Go functions

### ISSUE THREAD

**Issue by mlvzk** [ul/kak-lsp#338]
I saw this before in comments for libraries, but now I noticed it displays incorrectly even for Go builtin functions.

I use gopls(commit 897954058703b4fa73f6a222681cb08ff55be85d) and go v1.14.1

Here is where the function is defined: https://github.com/golang/go/blob/ad6c691542e2d842c90e2f7870021d16ffa71878/src/builtin/builtin.go#L189

A golang contributor said it's a problem with clients(in that issue's case lsp-mode): https://github.com/golang/go/issues/38656#issuecomment-619411176

![image](https://user-images.githubusercontent.com/44906333/82502835-5b25eb00-9af8-11ea-9820-348c3738fdbb.png)

**Comment by ul** [comment]
Would you mind trying with the latest kak-lsp master? We are requesting hover in plaintext, but it seems that there were a few places where this option should be set, and they all were filled in only recently in #330

**Comment by mlvzk** [comment]
Yep, works on master. Thanks for the very quick response!
![image](https://user-images.githubusercontent.com/44906333/82504383-84944600-9afb-11ea-93eb-77d4928fbf19.png)
