### ISSUE TITLE
colorProvider out of spec?

### ISSUE THREAD

**Issue by mreppen** [ul/kak-lsp#357]
Based on the discussion [here](https://github.com/julia-vscode/LanguageServer.jl/issues/730#issuecomment-636265898), kak-lsp's initialization is not conforming with spec.

`kak-lsp` sends `"colorProvider": null,` during initialization. Based on the discussion above, this should be `true`, `false`, or omitted.

The spec itself: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_documentColor

**Comment by ul** [comment]
I believe this was fixed back in https://github.com/ul/kak-lsp/pull/336. kak-lsp sends
```
"colorProvider": {
  "dynamicRegistration": false
}
```
as part of client capabilities.

It hasn't made into release yet tho.

**Comment by mreppen** [comment]
That's great; my bad for only running the latest release. I tried the latest git commit and this null-bug does no longer occur.

Only `lsp-diagnostics` works, so I have more debugging ahead of me.

@ul Thanks for a great plugin. It bridges the last gaps from last time I tried kak and allowed me to switch.
