### ISSUE TITLE
Elm completion incorrect after period

### ISSUE THREAD

**Issue by Parasrah** [ul/kak-lsp#358]
Hi! First off, really like this tool, thanks for all your hard work! I've just started using Kakoune more seriously lately, and have the lsp installed via `plug.kak`, and noticed the following happens when selecting a completion item in `elm`:

![image](https://user-images.githubusercontent.com/14935550/84200982-cbbf8800-aa64-11ea-930e-b70a69eaf25f.png)

![image](https://user-images.githubusercontent.com/14935550/84201030-e2fe7580-aa64-11ea-8db0-f95a9bef1ca4.png)

It seems whenever I perform a completion after a `.`, it ignores everything that precedes the `.` and inserts the whole item. It's not hard to work around (by just writing the actual thing I want, in this case `stringRes` instead of `Http.stringReso`) but I figured I'd mention it anyways. I looked around for duplicates and didn't see any similar items, but sorry in advance if I missed one!

kak-lsp commit: `23e229eb1ba649697af0c9895001cb161e3d4d04`
kakoune commit: `6fa26b8dd2ac0931fe688370728c47086277d883`

Thanks again!

**Comment by ul** [comment]
Hello! Thank you for your kind words! Would you mind posting kak-lsp log for when this problem happens? You can find how to obtain the log here https://github.com/ul/kak-lsp#troubleshooting

**Comment by Parasrah** [comment]
Will try to get a log tomorrow for it 👍

**Comment by Parasrah** [comment]
[kak-lsp.log](https://github.com/ul/kak-lsp/files/4784139/kak-lsp.log)

I replaced occurrences of my directory with `<root_dir>`, and didn't see any other sensitive info in the logs. That said the file is fairly large, so if you know of any sensitive information that might be in it let me know. This was just from the ~5 seconds it took me to complete the `Http.stringResolver` in the same way above and then exit. There is a ton of code in there that I'm not worried about (it's open source anyways)

Thanks again!

**Comment by ul** [comment]
There are two things in play here: first of all, the fact that kak-lsp doesn't support `textEdit` yet (see #40) which is the way to go these days and Elm language server expect it to be used. As a result, it omits `insertText` and sets `label` to `Http.stringResolver` — which is used by kak-lsp as a completion text in this scenario. And second, kak-lsp assumes that completed fragment starts after the `.`.

Until #40 is solved you may use a workaround. I just pushed support for it to the master.

Idea is to customise `lsp_completion_fragment_start` to change how the fragment start is detected, so it would include `.`. It could look smth like this:

```
hook global WinSetOption filetype=elm %{
  set-option buffer lsp_completion_fragment_start %{execute-keys <esc><a-h>s\$?[\w.]+.\z<ret>}
}
```

I was unable to test it properly, please let me know if it does or doesn't work for you.

**Comment by Parasrah** [comment]
Awesome thanks! I will give that a shot next time I can make some time to work on that app and let you know if it works or not. If not I'm completely ok waiting for #40, I'm not in any rush and have a decent workaround for the time being. Thanks again!

**Comment by Parasrah** [comment]
btw @ul Just tested it briefly but it seemed to work! Thanks!
