### ISSUE TITLE
Setting different options for lsp_show_hover_format per key

### ISSUE THREAD

**Issue by Parasrah** [ul/kak-lsp#359]
Hi, I'm trying to set it up so in user mode, pressing `k` will show info and pressing `K` will show diagnostics. I set up a hook for entering user mode, that in turn creates a hook for the raw key being pressed as follows:

```kak
hook global ModeChange push:normal:next-key\[user-mapping\] %{
    echo -debug Entered User Mode
    hook global -group lsp-hover RawKey .* %{
        echo -debug got %val{hook_param}
    }
}
```

and the hook on exit:

```kak
hook global ModeChange pop:next-key\[user-mapping\]:normal %{
    echo -debug Left User Mode
    remove-hooks global lsp-hover
}
```

Unfortunately this doesn't work because the `ModeChange pop...` hook occurs before the `RawKey .*` hook. Right now I've bypassed this by just skipping the `ModeChange` hooks altogether:

```kak
hook global RawKey k %{
    echo -debug Pressed %val{hook_param}
    set-option buffer lsp_show_hover_format 'printf %s "${lsp_info}"'
}

hook global RawKey K %{
    echo -debug Pressed %val{hook_param}
    set-option buffer lsp_show_hover_format 'printf %s "${lsp_diagnostics}"'
}
```

I'd prefer not to do this because it's now being triggered every time I press `K` or `k`, but it's working for now. I was just wondering if I'm going about this the wrong way.

This might not really be `kak-lsp` specific, feel free to close if I should be asking this on the discourse instead. Thanks!

**Comment by Delapouite** [comment]
Hello.

I may have misunderstood what you're trying to achieve, but what about:

```
map global lsp k %{ : set-option buffer lsp_show_hover_format 'printf %s "${lsp_info}"' <ret> } -docstring 'show hover info'
map global lsp K %{ : set-option buffer lsp_show_hover_format 'printf %s "${lsp_diagnostics}"' <ret> } -docstring 'show hover diagnostics'
```

This way you could type, assuming that you have map the `lsp` user-mode on the `l` key of the default user mode:
`,lk` or `,lK`.

**Comment by ul** [comment]
If you manually trigger `lsp-hover` then yes, I think the best way is to just extend it with setting format first and then calling `lsp-hover`. Something like this:

```
define-command lsp-hover-info -docstring "show hover info" %{
  set-option buffer lsp_show_hover_format 'printf %s "${lsp_info}"
  lsp-hover
}

define-command lsp-hover-diagnostics -docstring "show hover info" %{
  set-option buffer lsp_show_hover_format 'printf %s "${lsp_diagnostics}"'
  lsp-hover
}

map global lsp k %{ : lsp-hover-info<ret> } -docstring 'show hover info'
map global lsp K %{ : lsp-hover-diagnostics<ret> } -docstring 'show hover diagnostics'
```

**Comment by Parasrah** [comment]
Ok thanks for the help, I'll give that a shot tomorrow!
