### ISSUE TITLE
Manually triggering completions

### ISSUE THREAD

**Issue by zovt** [ul/kak-lsp#366]
Hello, I've been combing through the docs and source code, but I can't seem to figure out how to achieve the desired behavior. Basically, I'd like to disable the automatic completion triggers, and only trigger them manually (preferably through <c-n> in insert mode). So far, I've done:
```
set global lsp_completion_trigger %{ fail }
```
Which successfully disabled the autocomplete prompts, however, I can't seem to figure out the best way to trigger them manually. <c-n> seems to be using the default kakoune completion.

Is what I'm trying to accomplish possible currently?

Thanks!

**Comment by ul** [comment]
`lsp_completion_trigger` is responsible for the decision to send or not request for a particular place in the code after `lsp-completion` was called, either manually or automatically.

`lsp-completion` itself is called automatically because it's hooked to `InsertIdle` by `lsp-enable-window` https://github.com/ul/kak-lsp/blob/master/rc/lsp.kak#L1331

Unfortunately, currently it's impossible to disable only this particular hook. However, you can just copy-paste `lsp-enable-window` in your `kakrc` instead of calling it and remove the line which registers the hook.

**Comment by zovt** [comment]
That approach also works to disable the automatic popups, but how can I trigger the popup manually?

**Comment by ul** [comment]
If I correctly understand your question then you can add something like this in your config:
```
map global insert <c-t> '<a-;>: lsp-completion<ret>'
```
this would trigger a popup on <kbd>Ctrl</kbd>+<kbd>T</kbd>

**Comment by zovt** [comment]
That doesn't seem to work, I don't get a popup. Manually running `: lsp completion` doesn't do anything either. For reference, these are the lines related to the lsp that I have in my kakrc:
```
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|c|cpp) %{
    set-option window completers option=lsp_completions %opt{completers}

    add-highlighter window/cquery_semhl ranges cquery_semhl
    add-highlighter window/lsp_references ranges lsp_references
    add-highlighter window/lsp_semantic_highlighting ranges lsp_semantic_highlighting
    add-highlighter window/lsp_semantic_tokens ranges lsp_semantic_tokens
    add-highlighter window/rust_analyzer_inlay_hints replace-ranges rust_analyzer_inlay_hints

    lsp-inline-diagnostics-enable window
    lsp-diagnostic-lines-enable window

    map window goto d '<esc>: lsp-definition<ret>' -docstring 'definition'
    map window goto r '<esc>: lsp-references<ret>' -docstring 'references'
    map window goto y '<esc>: lsp-type-definition<ret>' -docstring 'type definition'

    hook -group lsp window WinClose .* lsp-did-close
    hook -group lsp window BufWritePost .* lsp-did-save
    hook -group lsp window WinSetOption lsp_server_configuration=.* lsp-did-change-config
    hook -group lsp window NormalIdle .* %{
        lsp-did-change
        %sh{if $kak_opt_lsp_auto_highlight_references; then echo "lsp-highlight-references"; else echo "nop"; fi}
    }

    lsp-did-open
    lsp-did-change-config
    map window lsp D ': lsp-diagnostics<ret>' -docstring "Show diagnostics"
    map window insert <c-t> '<a-;>: lsp-completion<ret>'
}
```
Let me know if I missed something or am doing something incorrectly.

**Comment by ul** [comment]
Config looks good to me. It seems that Kakoune's completion itself is not triggering. Might worth trying `<c-o>` for toggling it. If that would help then you can incorporate it into a binding so you don't need to press both:
```
map window insert <c-o> '<a-;>: lsp-completion<ret><c-o>'
```

**Comment by zovt** [comment]
There were a few issues with the hook, this is what I've got currently which seems to work pretty well
```
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|c|cpp) %{
	set-option window completers option=lsp_completions	%opt{completers}

	add-highlighter	window/cquery_semhl	ranges cquery_semhl
	add-highlighter	window/lsp_references ranges lsp_references
	add-highlighter	window/lsp_semantic_highlighting ranges	lsp_semantic_highlighting

	lsp-inline-diagnostics-enable window
	lsp-diagnostic-lines-enable	window

	map	window goto	d '<esc>: lsp-definition<ret>' -docstring 'definition'
	map	window goto	r '<esc>: lsp-references<ret>' -docstring 'references'
	map	window goto	y '<esc>: lsp-type-definition<ret>'	-docstring 'type definition'

	hook -group	lsp	window WinClose	.* lsp-did-close
	hook -group	lsp	window BufWritePost	.* lsp-did-save
	hook -group	lsp	window WinSetOption	lsp_server_configuration=.*	lsp-did-change-config
	hook -group	lsp	window NormalIdle .* %{
		lsp-did-change
		%sh{if $kak_opt_lsp_auto_highlight_references; then	echo "lsp-highlight-references"; else echo "nop"; fi}
	}

	lsp-did-open
	lsp-did-change-config

	map	window insert <c-t>	'<a-;>:	lsp-completion<ret><c-o>'
	map	window lsp D ':	lsp-diagnostics<ret>' -docstring 'Show diagnostics'
}
```
Thanks for the help!
