### ISSUE TITLE
Publish diagnostics into *diagnostics* buffer

### ISSUE THREAD

**Issue by ul** [ul/kak-lsp#37]
Good to have a list of problems in entire project, not only see them inline.

**Comment by occivink** [comment]
Are multiple projects relevant in that context? If I understand correctly, `lsp-diagnostics` would be a command similar to `lsp-references` that opens a buffer containing the diagnostics for the current project, right? That doesn't sound too messy to me.

**Comment by ul** [comment]
@occivink that sounds reasonable, I had auto-publishing in my mind (the same way as inline diagnostics are published at the moment), but having it on-demand would be much better.

**Comment by ul** [comment]
Implemented in the most naive way, please let me know if you hit any troubles with it.
