### ISSUE TITLE
kak-lsp org

### ISSUE THREAD

**Issue by blaggacao** [ul/kak-lsp#377]
https://github.com/kak-lsp is still not taken.

I'm suggesting to constitute a gathering point similar to https://github.com/emacs-lsp

Specifically it might start making sense since there is https://github.com/emacs-lsp/dap-mode (debug adapter protocol).

That's work, sure. Please content acknowledging the idea and feel free to close this issue.

**Comment by ul** [comment]
Yes, that sounds good to me, it also would reflect better the fact that kak-lsp becomes more community-driven that it was initially. I registered org, will move the repo soon-ish.
