### ISSUE TITLE
Change default language server for C/C++

### ISSUE THREAD

**Issue by Screwtapello** [ul/kak-lsp#380]
Today, the default language server for C and C++ is cquery, but the cquery [repository](https://github.com/jacobdufault/cquery) is archived, and the README has a message at the top:

> cquery is no longer under development. clangd and ccls are both good replacements.

ccls might be a good new default, since apparently it's a fork of cquery.

clangd would also be a good new default, because it's an official LLVM project, presumably with the financial support that implies, and should be available everywhere that clang is.

**Comment by topisani** [comment]
I definitely vote for clangd - At this point i'm fairly certain it has the most features (that we support anyway), and the official backing makes it a good default choice.

It's also what i've been using daily for the past half a year or so, and where most of the features ive worked on in `kak-lsp` have been tested, so it should be fairly stable.

**Comment by sidkshatriya** [comment]
I vote for `clangd` too.  Additionally it's easily installable via the ubuntu 20.04 package manager ( `sudo apt install clangd`) and ubuntu is quite a popular distro as you know...

**Comment by bcortier-devolutions** [comment]
I'm also using `clangd` daily at work, it's great.

**Comment by ul** [comment]
Hey folks, I'd be happy to accept PR with any option you've got consensus for as I personally write close to zero C/C++ code, so haven't got any opinion.
