### ISSUE TITLE
Make zero char completion smarter

### ISSUE THREAD

**Issue by ul** [ul/kak-lsp#48]
We might want to have mode when after dot or other completion triggers it's enabled, but disabled after whitespace.

**Comment by ul** [comment]
As an alternative:

30-Wed 14:11:26	mawww_imc	Maybe there should be two settings: a list of character after which to trigger completion, and the number of characters of a word before triggering completion
30-Wed 14:12:30	mawww_imc	That would permit to disable word based completion by putting that number of char to a high value, while still having completion triggerring on . : and -> (for C++, set that to over value for other languages)

**Comment by maximbaz** [comment]
@ul, I was searching for how to enable completions right after pressing `.` and stumbled upon this ticket - is it supposed to work? I've tried with Go and Python language servers, in both cases I must type at least one character before I get an autocomplete box, is it possible to get autocomplete show up immediately after typing `.`?

**Comment by ul** [comment]
Sorry, it seems I broke it in 53b0ca4a, now should be fixed. Ref. #202

**Comment by maximbaz** [comment]
I see, thanks! 

By the way, were there no news about a new kakoune release, will 6.2.1 still stay in pre-release mode?

**Comment by ul** [comment]
Yes, I was waiting for artifacts to appear to change release to pre-release (GitHub doesn't allow editing of empty release for somewhat reason).
