### ISSUE TITLE
Provide convenient restart-after-crash-or-timeout for session model

### ISSUE THREAD

**Issue by ul** [ul/kak-lsp#52]
If kak-lsp was crashed or exited by timeout after certain period of user inactivity then its restart should be automated. Current integration with Kakoune provides only automatic start on Kakoune session start and `lsp-start` command to restart manually.

**Comment by Screwtapello** [comment]
Ideally, when Kakoune calls `kak-lsp`, it should provide enough information to reconnect to an existing session *or* start a new one as needed, so `kak-lsp` can silently and automatically do the right thing.

(this may already be the case, I haven't checked, sorry)

**Comment by ul** [comment]
I pushed naive implementation, let me know if you'll have any troubles with it.
