### ISSUE TITLE
Periodically seeing "unclosed face definition" in *debug* buffer

### ISSUE THREAD

**Issue by schickm** [ul/kak-lsp#536]
Hello, 

Let me first start by saying thank you for the wonderful software.  `kak-lsp` is the part of the kakoune ecosystem that, for me, makes the editor feel on par with the tools integrations provided by something like vscode. 

I currently only use kak-lsp with Typescript (via [typescript-language-server](https://github.com/typescript-language-server/typescript-language-server)).  Everything seems to work as expected, however sometimes I don't see the info box popup as expected (when I have `:lsp-autohover-enable`).  

Given the following code:
```
const layer = {
  src: "dark.png",
  log: true
};
```

When I place my cursor over any part of the `layer` variable name, then I end up seeing the following in the `*debug*` buffer:

```
error running command 'eval -client client0 -verbatim -- lsp-show-hover 3.11 %§{InfoBlock}const layer: {
    src: string;
    log: boolean;
}{InfoDefault}§ %§§': 1:1: 'eval': 1:2: 'evaluate-commands': 1:1: 'info': unclosed face definition
``` 

It seems pretty clear to me that this is due to my language server ([typescript-language-server](https://github.com/typescript-language-server/typescript-language-server)) wanting to send back text that includes `{...}`, which then causes Kakoune to interpret it as a markup string.  I'll also note that I've seen this happen with using [Deno](https://deno.com/) as a language server as well.  My guess is that it happens with any language server that ever wants to return some text with something like `{Foo bar baz}` in it.

So my question is....am I correct in that this is just a lack of character escaping issue?  And....any recommendation as to how to deal with it?  I found [the kakoune docs for how to actually escape them](https://github.com/mawww/kakoune/blob/master/doc/pages/faces.asciidoc#markup-strings), but I'm not sure exactly if `kak-lsp` has any support for doing this...maybe this isn't considered the domain of `kak-lsp`?

**Comment by krobelus** [comment]
Simple escaping issue - the argument to `lsp-show-hover` must be a valid markup string. Thanks for reporting!

we still don't have a typescript server in the default config. We should probably add at least the most popular one, I'm not sure which one that is

**Comment by schickm** [comment]
Hot damn that was fast turn around! Thank you so much @krobelus!
