### ISSUE TITLE
Thoughts about inline diagnostics

### ISSUE THREAD

**Issue by casimir** [ul/kak-lsp#54]
Due to complaints from several users (me included) inline diagnostics has been disabled by default in a89a2e1b142e06d43a0d8395e50a316a6fc1ac00. I think most users expect to have this enabled by default when using LSP and that disabling it provides a worse first experience.

Also I'd like to point that people most likely don't complain about the feature on itself but that  diagnostics that are too visible. I think this is due to the choice of the faces used. For example `Information` is really annoying in a buffer when using the gruvbox theme since the face is the same than the one of the main cursor. I guess `Information` is more adapted for UI components like the info box than to display inline information.

The ideal solution UX-wise would be colored underline but this is pretty difficult to display in a terminal screen if not impossible. Testing with similar setups in other editors I found using only a foreground color to be the more adapted. Particularly with yellow for information and red for errors, a couple that work with most of color schemes.

In the end it would be useful to allow users to configure the faces used by kak-lsp, something like `DiagnosticInfo` and `DiagError` maybe? @mawww would it be overkill to add these as default faces in kakoune? That way it could be theme-specific.

**Comment by ul** [comment]
Thanks for starting this thread! Yes, now I also tend to think that for the first experience it would be nice to have this feature enabled and just have a way to customize or disable to be easily discoverable.

Perhaps no need to add faces to Kakoune itself, we can just define them in lsp.kak defaulting to Error/Information (is it possible to use one face to define another?) and describe in docs how to customize them.
