### ISSUE TITLE
SyncTeX inverse search in texlab doesn't work

### ISSUE THREAD

**Issue by malte-v** [ul/kak-lsp#603]
The support for SyncTeX inverse search introduced by #577 doesn't work for me. When I Ctrl+LeftClick in zathura, this appears in the debug buffer:
```
error running command '
                evaluate-commands -client  %{   // <- "$kak_client" should get expanded here
                    evaluate-commands -try-client %opt{jumpclient} %{
                        edit -- /home/malte/repos/bwinf-runde2/aufgabe3/doc/aufgabe3.tex 3
                    }
                }
            
': 2:17: 'evaluate-commands': wrong argument count
```
Apparently the `$kak_client` environment variable gets lost somehow, but I'm not sure how to fix it.

cc @krobelus

**Comment by krobelus** [comment]
My bad, this error happens when `lsp-enable` is run without a client in context (i.e. while sourcing kakrc).
So a workaround is to run `lsp-disable` followed by `lsp-enable` and another `texlab-forward-search`.

The current implementation is quite hacky, I'll try to think of a fix.
