### ISSUE TITLE
Visually separate different tooltips for a given line

### ISSUE THREAD

**Issue by Screwtapello** [ul/kak-lsp#66]
Currently, if the LSP server provides multiple tooltips for a given line, `kak-lsp` just concatenates them. This is not a bad approach, but Rust's LSP in particular likes to provide multi-line tooltips with blank lines for spacing, so I often get something like:

    first message says a thing
    second message description

    second message hint or suggestion
    third message is here too

...which I try to parse as two two-line messages instead of three messages.

One solution would be to add hyphens between each message, but that would also take up a lot of vertical space, and Kakoune's info boxes are pretty chunky already:

    first message says a thing
    ----
    second message description

    second message hint or suggestion
    ----
    third message is here too

Another solution would be to turn the messages into a bulleted list, by adding a bullet and a space to the beginning of each message, and two spaces after each newline. Using the standard Unicode bullet character U+2022 BULLET (many other options are available):

    • first message says a thing
    • second message description

      second message hint or suggestion
    • third message is here too

I think that would take up less space overall

**Comment by ul** [comment]
I went with bullets as a more compact way, let me know if you will spot any troubles with them or any other way to improve hover info further.
