### ISSUE TITLE
files created with mktemp are not cleaned up if no language server is a available

### ISSUE THREAD

**Issue by JJK96** [ul/kak-lsp#67]
When a file that has no language server available, for example kakrc is edited. 
While typing in insert mode, new files in /tmp are created continually.
This is probably the result of the lsp-did-change command making a call to mktemp.

**Comment by ul** [comment]
Good catch! Fixed it, situation should improve further after #22 fix.

**Comment by JJK96** [comment]
It occurs less, however, especially for html files I still get this problem. I propose firstly to save the temporary files in the kak-lsp directory, that way the litter is less of a problem.

**Comment by ul** [comment]
@JJK96 yes, i will scope temp files by dir. I wonder why those files are not removed for html filetype
