### ISSUE TITLE
* character escaped

### ISSUE THREAD

**Issue by JJK96** [ul/kak-lsp#69]
In function definitions the * becomes \\*. 

For example: 
```
main(\*args, \*\*kwargs)
```

**Comment by ul** [comment]
Looks like language server sends markdown. Do you have ideas how to render it to plain text the best?

**Comment by JJK96** [comment]
Unless you want to implement a full markdown/html renderer I think the best option is to just remove all backslashes except if followed by a backslash.

so something like `'s/\\([^\])/\1/g'`

**Comment by JJK96** [comment]
A better option: 

In the [language server specification](https://microsoft.github.io/language-server-protocol/specification) there is a setting that tells what kind of MarkupKind you want to receive, plain or markdown.

**Comment by ul** [comment]
I'll definitely add proper client capabilities for it, but problem is that pyls ignores them and sends doc in markdown anyway, and even more, it does it in a plain string format, without providing a kind. The only robust way do detect that we need to do unescape in such situation is to add a configuration option which will force markdown unescape for a given server.

**Comment by ul** [comment]
Missed your comment and created an issue: https://github.com/palantir/python-language-server/issues/386

**Comment by ul** [comment]
I skimmed through https://github.com/palantir/python-language-server/pull/348/files — it looks like it will not respect documentationFormat client capability, but at least it will annotate documentation with proper `kind`.

**Comment by maximbaz** [comment]
@ul you added the client capability for `completion_item.documentation_format`, but there are two more places where this can be configured: `hover.contentFormat` and `signatureHelp.signatureInformation.documentationFormat`. Just want to confirm if whether it makes sense to add those as well (unless you already did so and I missed this commit).

**Comment by ul** [comment]
@maximbaz I does make sense to add them, I just overlooked it.
