### ISSUE TITLE
Put received log messages in *debug* buffer

### ISSUE THREAD

**Issue by maximbaz** [ul/kak-lsp#74]
`bash-language-server` can sometimes [write messages in log](https://github.com/mads-hartmann/bash-language-server/blob/6f1bbd0272dc6352330ba7f04fa1ccc115df28d6/server/src/server.ts#L117-L119), like so:

```
this.connection.console.log(
    'getExplainshellDocumentation returned: ' + JSON.stringify(response, null, 4),
)
```

In kakoune I'm being spammed with them in info box:

![image](https://user-images.githubusercontent.com/1177900/42657094-8f3bc380-8621-11e8-976e-6f3ec7a2125b.png)

Is the language server correctly reporting warnings? If not, what should it do instead? If yes, can we have these warnings appear in `*debug*` buffer instead?

**Comment by ul** [comment]
Errors from language servers which are not diagnostics are supposed to be rare and significant, that's why kak-lsp draws user attention by showing info box.

It might worth investigating what caused this error, and reporting a bug (either kak-lsp sends malformed request or bash language server doesn't handle your script properly).

That said, when reporting an error kak-lsp calls [`lsp-show-error`](https://github.com/ul/kak-lsp/blob/master/rc/lsp.kak#L224) on Kakoune side and you can override it in your `kakrc`:

```
def -override -hidden lsp-show-error -params 1 -docstring "Render error" %{
    echo -debug "kak-lsp:" %arg{1}
}
```

This way error will be reported only in `*debug*` buffer.

**Comment by maximbaz** [comment]
That language server has two external sources of information, let's call them a "good one" and a "basic one". In this case the `console.log` happens when the "good" source is unavailable, so while the language server falls back to the "basic" source, it also prints some extra details in `console.log` to help you investigate the issue. The thing is, sometimes this is not an issue and my "good" source is intentionally disabled. 

I noticed that there is also `console.error` — that definitely is reserved for errors and makes sense to show in the info box, and I want to keep seeing them in the info box. But what about `console.log`, do you think that is an inappropriate place for a language server to write some extra diagnostic information? Can we even distinguish the messages coming from `console.error` and `console.log`?

**Comment by ul** [comment]
`lsp-show-error` at the moment is called only when language server sends error response. I think error shown on the screenshot has nothing to do with the linked `console.log` invocation. Looks like it's result of language server catch-all error handler which sends back error response if exception was thrown in request handler.

Would you mind providing me with steps to reproduce problem? Then I'll be able to say something more definite about its nature and possible solutions.

**Comment by maximbaz** [comment]
Of course you were right, the error on the screenshot has nothing to do with the `console.log`. So sorry for the confusion, I should have paid closer attention to the code before opening the issue.
