### ISSUE TITLE
Formatting support

### ISSUE THREAD

**Issue by sebsebmc** [ul/kak-lsp#76]
I am interested in getting textDocument/formatting support working. There was some talk in the #kakoune IRC about it a few days ago.

**Comment by ul** [comment]
That would be great! Would you like to go with implementation?

**Comment by maximbaz** [comment]
Wow this is just awesome, thanks for implementing @ul 🙂

**Comment by ul** [comment]
Re-opening because it's broken, text edit is not implemented properly.
