### ISSUE TITLE
Question: is `lsp-formatting` intentionally async?

### ISSUE THREAD

**Issue by maximbaz** [ul/kak-lsp#83]
I was hoping to configure something like this to have my go file automatically formatted on save:

```
hook global WinSetOption filetype=go %{
    hook window -group format BufWritePre .* lsp-formatting
}
```

However right now it seems my file is being saved before formatting occurs. 

Formatting is something that should probably be synchronous in general, I wouldn't want to start editing a file before it is reformatted, or I would risk losing my changes.

**Comment by ul** [comment]
Yes, that's how kak-lsp is built at the moment, responses to all requests are delivered asynchronously via `kak -p`. I think it's a fairly big change to introduce synchronous request-response into current architecture, but we can think about some kind of workaround. For example creating flag-like named pipe and block client by reading from it until response arrives and writes into pipe.

**Comment by maximbaz** [comment]
Wow nice, thanks a lot, I'll try this tomorrow 👍 

By the way, I was meaning to tell you, `lsp-formatting` as a command name sounds a bit weird to my ear, I feel a verbal structure `lsp-format` would have been a better choice 🙂

**Comment by ul** [comment]
I feel the same, but I'm trying to keep names of commands which have direct LSP methods counterparts as close as possible to those methods.

**Comment by ul** [comment]
Though I think it's a good idea to create pleasant aliases for them (PR is welcome 😉)
