### ISSUE TITLE
 'lsp-enable' 2:6: 'set' wrong argument count

### ISSUE THREAD

**Issue by Epictek** [ul/kak-lsp#85]
I've put this in my kakrc
`%sh{kak-lsp --kakoune -s $kak_session}`

but I get this error
```
/home/kieran/.config/kak/kakrc:397:13328: 'lsp-enable' 2:6: 'set' wrong argument count
/usr/share/kak/kakrc:87:12585: 'source' 397:13328: 'lsp-enable' 2:6: 'set' wrong argument count
error while parsing kakrc:
    1:1: 'source' 87:12585: 'source' 397:13328: 'lsp-enable' 2:6: 'set' wrong argument count
```

Also tried 
`eval %sh{kak-lsp --kakoune -s $kak_session}`
and got the same error 
```
/home/kieran/.config/kak/kakrc:1:1: 'eval' wrong argument count
/usr/share/kak/kakrc:87:12585: 'source' 1:1: 'eval' wrong argument count
error while parsing kakrc:
    1:1: 'source' 87:12585: 'source' 1:1: 'eval' wrong argument count

```

**Comment by ul** [comment]
Sounds like you have pre-big-breaking-changes version of Kakoune. One option is to build Kakoune from the git repo, and another is to use kak-lsp version 4 — it has less features than 5, but is compatible with older Kakoune.

**Comment by Epictek** [comment]
Oh wow didn't realise that the "stable" release was so out of date, changed to the git version and it works fine. Thanks for the help.
