### ISSUE TITLE
Support the DidChangeConfiguration notification

### ISSUE THREAD

**Issue by Screwtapello** [ul/kak-lsp#86]
The LSP spec defines [a DidChangeConfiguration notification](https://microsoft.github.io/language-server-protocol/specification#workspace_didChangeConfiguration) which tells the language server about language-specific configuration. For example, with the Rust Language Server, you can set [a whole bunch of options](https://github.com/rust-lang-nursery/rls#configuration) to configure how it works for a particular project. It would be great for kak-lsp to expose a way for the user to set these configuration options in Kakoune.

A suggested design:

- kak-lsp declares a new option `lsp_server_configuration` of type `str-to-str-map`, whose keys are of the form "language.varname" (`rust.clippy_preference`) and whose values are interpreted as JSON values: anything that can be parsed as JSON is that JSON value, anything else is treated as a string.
- when kak-lsp is enabled for a particular window, add a `WinSetOption lsp_server_configuration=.*` hook that grabs the contents of `lsp_server_configuration` (or at least, the keys that begin with the current language name) and send it to the language server as a DidChangeConfiguration message.

Possible extensions:

- When the language server sends [a Configuration request](https://microsoft.github.io/language-server-protocol/specification#workspace_configuration), grab the current contents of the `lsp_server_configuration` option and if any of the requested configuration items are present, send them as the response.
    - This is a big ol' race-condition between the language server, kak-lsp and the Kakoune hooks that set options when you open a file, but with a WinSetOption hook hopefully it will all sort itself out?
- If there are "well known" config options supported by many language servers (tab width? line length?), and Kakoune also has options that configure the same thing, (`indentwidth`, `autowrap_column`), consult those too (and add hooks to catch updates)
- When the Configuration request arrives, if any requested configuration items do *not* exist in `lsp_server_configuration`,  add them with an empty value (at the Window scope), so that users can figure out what configuration options exist for their buffer with `debug options`
- list config options in the output of `lsp-capabilities` since that's another place people might look for information about what kak-lsp can do for a given buffer

Alternatives:

- Instead of a single `lsp_server_configuration` map, you could define individual options like `lsp_server_rust_clippy_preference`. This would make it even easier to explore the options a language server provides, and allow Kakoune to validate option types (boolean true versus the string "true", for example). The downside is that such options could not easily be set from "kakrc" since they wouldn't exist until after the language server was started up.
- Since Kakoune already implements scoping, we may not need to use "language.varname" keys to keep language-specific settings separate. However, [apparently VS Code uses that convention](https://www.reddit.com/r/rust/comments/98gqsg/announcing_the_rls_10_release_candidate/e4hqu8c/) so if kak-lsp does the same thing, it'll be easier for kak-lsp users to follow documentation written for VS Code.

**Comment by Screwtapello** [comment]
It's easy enough to add project-specific configuration to Kakoune: just put something like:

```kak
%sh{ test -f .kak/kakrc && printf "source .kak/kakrc\n" }
```

...in your regular kakrc. At any rate, if somebody wants project-specific configuration, they need to solve that problem for Kakoune in general, and kak-lsp can build off that.

**Comment by ul** [comment]
Sounds reasonable. Would you like to go with implementation?

**Comment by Screwtapello** [comment]
It turns out that Kakoune does not currently support custom options of type `str-to-str-map`; `ui_options` is the only such option allowed. On IRC, @mawww  said:

> Yeah, I dont think this type was made available to used declared options. Could be if we had a good reason, I am not sure it is significantly better than a str-list though
> (as we do not have any way to index into the list, I think the only advantage is that we can guarantee unicity of keys)

I'm not sure if this counts as a good reason, and even if it does I'm not sure how difficult it would be to get this working in Kakoune. Perhaps we could use a `str-list` option instead, with the convention that everything to the left of the first `=` is the key and everything to the right is the value... but when multiple items with the same key are present, which takes precedence?

**Comment by ul** [comment]
If we are going to encode key-value pairs as a list, then two thoughts pop up in my mind:

* let's just do actual pairs, no need to litter list with `=` elements
* if I do two `set -add` for two pairs with the same key, then the second pair should take precedence when the list is interpreted by kak-lsp; and it looks like it should be the rightmost pair because according to documentation "set -add appends the new element to the list"

**Comment by ul** [comment]
But you are right we need to figure out what Kakoune does with lists when it comes to scopes.

**Comment by Screwtapello** [comment]
I made a PR to add custom `str-to-str-map` options to Kakoune, since it turned out to be much easier than I expected. If it gets accepted we can use it, otherwise I'll need to investigate `str-list`s more closely.

**Comment by Screwtapello** [comment]
The Kakoune PR got merged, so I started looking into this. First the good news: I actually got it working, at least for RLS and the `clippy_preference` option. Now for the bad news:

- Unlike other messages, the only parameter `workspace/DidChangeConfiguration` takes is "settings", which can be literally any JSON type, including arbitrarily-nested types.
- I tried just putting the `lsp_server_configuration` map into a TOML `[params.settings]` table, but Rust wouldn't let me: talking to the language server requires a `serde_json::Value` while the request from Kakoune gave me a `toml::Value`, and although I could convert via Serde, I had to `.clone()` to make it work.
- This means that the `lsp_server_configuration` values need to be TOML syntax, so kak-lsp can convert them to JSON syntax. If you say `foo=6` in Kakoune, the language server gets `serde_json::Number(6)`, but if you say `foo="6"` the language server gets `String::new("6")`.
- However, the `rust.clippy_preference=on` setting I mentioned in the OP actually needs to be transmitted as the JSON `{"rust": {"clippy_preference": "on"}}`. Translating back to TOML syntax and to Kakoune's map syntax, that would be `rust={clippy_preference="on"}`. Unfortunately, it turns out that Kakoune does not allow the `=` in either the key or the value of a map, so this cannot work.
- However, if people refer to this setting as `rust.clippy_preference`, maybe we can just use that syntax for Kakoune? I changed `lsp.kak` to turn `rust.clippy_preference="on"` into:

        [params.settings.rust]
        clippy_preference="on"

- At that point, things worked!
- Unfortunately, some language servers have *much* more deeply-nested settings. If I'm reading [this python-language-server code](https://github.com/palantir/python-language-server/blob/develop/vscode-client/package.json#L19) correctly, `pyls.plugins.jedi_completion.enabled` is a setting somebody might want to set.
- It wouldn't be difficult to turn the single setting `pyls.plugins.jedi_completion.enabled=true` into a TOML table heading and a key, but for multiple settings TOML has very restrictive rules about the order of keys and tables; rules I don't think I can implement in raw POSIX shell.

I think the way forward is to have `lsp.kak` turn this Kakoune option value:

    set global lsp_server_configuration \
        rust.clippy_preference="on" \
        pyls.plugins.jedi_completion.enabled=true

...into this TOML:

    [params.settings]
    "rust.clippy_preference"="on"
    "pyls.plugins.jedi_completion.enabled"=true

...and have kak-lsp do the work of converting that into a tree of `serde_json::Map` values that can be sent on.

If you're interested I can push what I've got as a PR for early feedback, but I'll reworking it to try that new approach.

**Comment by ul** [comment]
Hello! Thanks for thorough investigation. I think that this is totally okay to put all conversion heavy lifting on kak-lsp side and allow having just dotted paths as keys on both kakrc and toml config sides. Any intermediate PR is more than welcome!
