### ISSUE TITLE
Feature req, lsp-references as highlighter?

### ISSUE THREAD

**Issue by vbauerster** [ul/kak-lsp#91]
It would be nice to have something like `lsp-auto-highlight-references` option, so it would highlight symbol references at main cursor point, after some (configurable)? delay.

PS: thank you for your great work!

**Comment by vbauerster** [comment]
Also if cursor moved away, highlights should disappear.

**Comment by ul** [comment]
Hello! I think it's a nice feature which is completely doable and should be even fairly easy to do, I will try to implement it once I'll get some time.

**Comment by ul** [comment]
Binaries at https://github.com/ul/kak-lsp/releases/tag/v5.4.0 should be available soon, let me know if you'll hit any bugs or have an idea of better default highlighting face.

`set global lsp_auto_highlight_references true` to enable this feature globally, `lsp-highlight-reference` to manually (or from another command) trigger highlighting. `set-face global Reference ...` to customize appearance.

**Comment by vbauerster** [comment]
Thank you Ruslan! It's a killer feature for me! Default face looks great with my light theme.
[![Screen_Shot_2018-10-03_at_11.14.06.png](https://i.postimg.cc/g2rgnzJ2/Screen_Shot_2018-10-03_at_11.14.06.png)](https://postimg.cc/zyZCQ1Ks)
