### ISSUE TITLE
[Feature Request] Show amount of lsp-diagnostic errors in status bar

### ISSUE THREAD

**Issue by JJK96** [ul/kak-lsp#94]
For me it would be beneficial to see at a glance if there are errors in the current file, instead of having to switch to the lsp-diagnostics buffer or scrolling through the file.

**Comment by ul** [comment]
Binaries should be available soon at https://github.com/ul/kak-lsp/releases/tag/v5.5.0
Just use `lsp_diagnostic_count` option in your modeline and voilà

**Comment by JJK96** [comment]
Thanks you very much
Such a quick response!

**Comment by JJK96** [comment]
Currently `lsp_diagnostic_count` contains the number of errors + the number of warnings. I would like to show only the number of errors in my status bar, maybe it is an option to have two variables?
