### ISSUE TITLE
[Feature request] next- and previous error

### ISSUE THREAD

**Issue by JJK96** [ul/kak-lsp#97]
Currently I find myself scrolling through the file to find where the error occurred, especially if I have edited in multiple places, and the error is not currently in my view. 

I think it would be nice to be able to jump to an error quickly.

It does not seem too hard to do since we have the lsp-diagnostics buffer which can just be parsed for the line and column of the error.

I will probably try implementing it myself soon.

Let me know your opinions

**Comment by ul** [comment]
It's easy to put a list of jump positions into an option when publishing diagnostics for the buffer. I think using that list would be easier than scanning `*diagnostics*` buffer. Do you want me to do Rust part, and you'll then implement Kakoune/shell part? (IIRC you are not interested much in Rust, but I may be wrong).

**Comment by JJK96** [comment]
Sure! I'll take a look at it soon.

**Comment by JJK96** [comment]
How about using the `lsp_errors` option as the jump list?

**Comment by ul** [comment]
Should be totally fine if it's convenient enough to parse. Idea with introducing another option was to ease Kakoune/shell side work, but not to introduce extra entity is generally better, of course.

**Comment by JJK96** [comment]
I think it should be easy to parse, since it is basically a list of coordinates including labels for the kind of diagnostic
