### ISSUE TITLE
'evaluate-commands' 131:15206: 'def' unknown option '-shell-candidates'

### ISSUE THREAD

**Issue by maximbaz** [ul/kak-lsp#99]
Just updated kakoune and kak-lsp and now this command:

```
evaluate-commands %sh{kak-lsp --kakoune -s $kak_session}
```

Throws this error:

```
'evaluate-commands' 131:15206: 'def' unknown option '-shell-candidates' 
```

Probably related to https://github.com/mawww/kakoune/pull/2419/, but I didn't have time to look into it to verify.

**Comment by ul** [comment]
Yes, it is related, thanks for heads up!

**Comment by dpc** [comment]
Hi @ul . This check does not seem to work on my NixOs system. My version is 2018.10.27, yet I still hit this error.

**Comment by dpc** [comment]
I can't figure out how to actually dispaly value of `$kak_version`

**Comment by ul** [comment]
Hey @dpc, you can try to execute `:echo %val{version}` in Kakoune itself, or, to double-check that env var is set, `:echo %sh{echo $kak_version}`.

**Comment by dpc** [comment]
BTW, I don't know if it's of any use, but I don't think `:echo %val{version}` works. I've used `:echo %sh{echo $kak_version}` instead.

**Comment by ul** [comment]
It seems that check fails because your `$kak_version` is without `v` prefix (e.g. on my system `$kak_version` is `v2018.10.27-28-g9bc893e7`). We can add handling for such case, but I wonder why it's different in the first place. @mawww is there any logic which decides to put or not `v` prefix to the `$kak_version`?

**Comment by dpc** [comment]
This is how this package is being built in NixOS: https://github.com/NixOS/nixpkgs/blob/9e8eea0f78ec2114dc872b62a051c034a3684e6d/pkgs/applications/editors/kakoune/default.nix

**Comment by maximbaz** [comment]
It is most certainly a fault of the way kakoune is packaged. 

Here's [how it's defined in kakoune's Makefile](https://github.com/mawww/kakoune/blob/9a68a2d3afa5d44961e04d7c4e1e0a0b568f4dee/src/Makefile#L23): first check what `.version` file contains (this file exists in release archive), if it doesn't exist, try to run `git describe --tags HEAD`.

However, you can overwrite this algorithm by passing version as an argument to `make`, and it seems this is what `nixOS` package is doing. Needs to be reported to them.

```
❯ version=aaa make
...                                                                                            
❯ ./kak -version                              
Kakoune aaa
```

**Comment by ul** [comment]
Thanks for clarification. It's quite fun that Nix passes `version` to `make` implicitly, I didn't expect that.

**Comment by maximbaz** [comment]
Me neither! And I'm not 100% sure this is what happens, but seems very likely 🙂

**Comment by dpc** [comment]
@utdemir might be able to help (I'm just looking at the history of the file)

**Comment by utdemir** [comment]
Hi. Yes, it looks like Nix automatically adds a `version` environment variable on the build environment. It is no big deal to make the version start with `v`, if there's tooling assuming that convention. I raised a [PR](https://github.com/NixOS/nixpkgs/pull/50617) to do that.
